-- Create tables for EPT 2G, 3G, 4G, and 5G site information

-- EPT 2G Table
CREATE TABLE IF NOT EXISTS EPT_2G (
    VENDOR VARCHAR(50),
    CELL_NAME VARCHAR(100) ,
    SITE_NAME VARCHAR(100),
    BSC VARCHAR(50),
    BCCH VARCHAR(50),
    BSIC VARCHAR(50),
    CELL_ID VARCHAR(50),
    LAC VARCHAR(50),
    FREQUENCE VARCHAR(50),
    AZIMUTH VARCHAR(50),
    LONGITUDE VARCHAR(50),
    LATITUDE VARCHAR(50),
    ARRONDISSEMENT VARCHAR(100),
    COMMUNE VARCHAR(100),
    DEPARTEMENT VARCHAR(100),
    PRIMARY KEY (VENDOR, CELL_NAME)
);

-- EPT 3G Table
CREATE TABLE IF NOT EXISTS EPT_3G (
    VENDOR VARCHAR(50),
    CELL_NAME VARCHAR(100) ,
    RBS_NAME VARCHAR(100),
    SITE_NAME VARCHAR(100),
    RNC VARCHAR(50),
    LAC VARCHAR(50),
    localcellid VARCHAR(50),
    ServiceArea VARCHAR(50),
    PSC VARCHAR(50),
    FREQ_BAND VARCHAR(50),
    BANDE VARCHAR(50),
    AZIMUTH VARCHAR(50),
    LONGITUDE VARCHAR(50),
    LATITUDE VARCHAR(50),
    ARRONDISSEMENT VARCHAR(100),
    COMMUNE VARCHAR(100),
    DEPARTEMENT VARCHAR(100),
    PRIMARY KEY (VENDOR, CELL_NAME)
);

-- EPT 4G Table
CREATE TABLE IF NOT EXISTS EPT_4G (
    VENDOR VARCHAR(50),
    CELL_NAME VARCHAR(100), 
    ERBS_Id VARCHAR(50),
    SITE_NAME VARCHAR(100),
    enodb_id VARCHAR(50),
    TAC VARCHAR(50),
    cell_id VARCHAR(50),
    dlchannelbandwidth VARCHAR(50),
    earfcndl VARCHAR(50),
    earfcnul VARCHAR(50),
    freq_band VARCHAR(50),
    PCI VARCHAR(50),
    ulchannelbandwidth VARCHAR(50),
    Bande VARCHAR(50),
    AZIMUTH VARCHAR(50),
    LONGITUDE VARCHAR(50),
    LATITUDE VARCHAR(50),
    ARRONDISSEMENT VARCHAR(100),
    COMMUNE VARCHAR(100),
    DEPARTEMENT VARCHAR(100),
    PRIMARY KEY (VENDOR, CELL_NAME)
);

-- EPT 5G Table
CREATE TABLE IF NOT EXISTS EPT_5G (
    VENDOR VARCHAR(50),
    CELL_NAME VARCHAR(100) ,
    gNodeB_name VARCHAR(100),
    SITE_NAME VARCHAR(100),
    gNBId VARCHAR(50),
    cellLocalId VARCHAR(50),
    nRPCI VARCHAR(50),
    nRTAC VARCHAR(50),
    NRSectorCarrierId VARCHAR(50),
    arfcnDL VARCHAR(50),
    arfcnUL VARCHAR(50),
    bSChannelBwDL VARCHAR(50),
    AZIMUTH VARCHAR(50),
    LONGITUDE VARCHAR(50),
    LATITUDE VARCHAR(50),
    ARRONDISSEMENT VARCHAR(100),
    COMMUNE VARCHAR(100),
    DEPARTEMENT VARCHAR(100),
    PRIMARY KEY (VENDOR, CELL_NAME)
);