"""
duck_manager.py
───────────────
Handles:
  - Creating tables in DuckDB from generated SQL
  - Inserting/refreshing data from MySQL into DuckDB in batches
  - Cleaning up rows older than N days
"""

import time as _time
import tempfile
import os

import duckdb
import mysql.connector
from datetime import date, timedelta, time as dt_time, datetime
import numpy as np


from config import MYSQL_CONFIG, DUCKDB_PATH, FETCH_BATCH_SIZE, LOAD_BATCH_DAYS
from logger import get_logger

logger = get_logger()


def _fix_row(row: tuple) -> tuple:
    """
    MySQL connector returns TIME columns as datetime.timedelta.
    DuckDB expects datetime.time — convert any timedelta value in the row.
    """
    result = []
    for val in row:
        if isinstance(val, timedelta):
            total_seconds = int(val.total_seconds())
            h = total_seconds // 3600
            m = (total_seconds % 3600) // 60
            s = total_seconds % 60
            result.append(dt_time(h, m, s))
        else:
            result.append(val)
    return tuple(result)


def _build_date_range(days_back: int = 1) -> tuple:
    today = date.today()
    return str(today - timedelta(days=days_back)), str(today)

def _date_batches(start_date: str, end_date: str, batch_days: int):
    """Yield (batch_start, batch_end) string pairs covering start_date..end_date."""
    current = datetime.strptime(start_date, "%Y-%m-%d").date()
    end     = datetime.strptime(end_date,   "%Y-%m-%d").date()
    while current <= end:
        batch_end = min(current + timedelta(days=batch_days - 1), end)
        yield str(current), str(batch_end)
        current = batch_end + timedelta(days=1)



# ─────────────────────────────────────────────────────────────
#  Table creation
# ─────────────────────────────────────────────────────────────

def create_all_tables(sqls: dict, duckdb_path: str = DUCKDB_PATH) -> None:
    """Create all tables in DuckDB from the generated SQL dict."""
    con = duckdb.connect(duckdb_path)
    try:
        for table_name, sql in sqls.items():
            if sql is None:
                print(f"  [SKIP] {table_name} — SQL generation failed earlier.")
                continue
            print(f"  Creating table: {table_name} ...", end=" ", flush=True)
            con.execute(sql)
            print("OK")
    finally:
        con.close()


def create_tables_from_file(sql_file: str, duckdb_path: str = DUCKDB_PATH) -> None:
    """
    Read the SQL file generated by Step 1 and execute each statement in DuckDB.
    Statements are separated by ';' — comments (--) are preserved but ignored at runtime.
    """
    with open(sql_file, "r", encoding="utf-8") as f:
        content = f.read()

    # split on ';' and filter out empty/comment-only blocks
    statements = [s.strip() for s in content.split(";") if s.strip()]

    con = duckdb.connect(duckdb_path)
    try:
        for stmt in statements:
            # extract table name from CREATE TABLE line for display
            table_name = "unknown"
            for line in stmt.splitlines():
                line = line.strip()
                if line.upper().startswith("CREATE TABLE"):
                    parts = line.split()
                    # CREATE TABLE IF NOT EXISTS <name>  or  CREATE TABLE <name>
                    table_name = parts[-1].strip("(")
                    break
            print(f"  Creating table: {table_name} ...", end=" ", flush=True)
            con.execute(stmt)
            print("OK")
    finally:
        con.close()


# ─────────────────────────────────────────────────────────────
#  Data insertion  (MySQL → DuckDB, batched)
# ─────────────────────────────────────────────────────────────

def load_table(table_config: dict, start_date: str, end_date: str, duckdb_path: str = DUCKDB_PATH) -> int:
    """
    Fetch rows from MySQL into a pandas DataFrame then bulk-insert into DuckDB.
    - DELETE existing rows for the date range first (clean replace)
    - pandas read is done in one shot — much faster than row-by-row executemany

    If date_col is set  -> fetch only start_date..end_date from MySQL.
    If date_col is None -> fetch the full table.

    Returns total rows inserted.
    """
    import pandas as pd

    table_name = table_config["mysql_table"]
    date_col   = table_config.get("date_col")

    t_total = _time.perf_counter()
    logger.info("load_table [%s] start: %s -> %s", table_name, start_date, end_date)

    # ── step 1 : MySQL connection ─────────────────────────────
    t0 = _time.perf_counter()
    mysql_conn = mysql.connector.connect(**MYSQL_CONFIG)
    print(f"  step 1  MySQL connect          : {_time.perf_counter()-t0:.3f}s")

    # ── step 2 : fetch rows ───────────────────────────────────
    t0 = _time.perf_counter()
    try:
        if date_col:
            query = f"SELECT * FROM `{table_name}` WHERE `{date_col}` BETWEEN %s AND %s"
            df = pd.read_sql(query, mysql_conn, params=(start_date, end_date))
        else:
            df = pd.read_sql(f"SELECT * FROM `{table_name}`", mysql_conn)
    finally:
        mysql_conn.close()
    total_rows = len(df)
    print(f"  step 2  MySQL fetch            : {_time.perf_counter()-t0:.3f}s  ({total_rows:,} rows)")

    if total_rows == 0:
        print("  Nothing to insert.")
        return 0

    # ── step 3 : replace empty strings ───────────────────────
    t0 = _time.perf_counter()
    df.replace("", np.nan, inplace=True)
    print(f"  step 3  replace empty strings  : {_time.perf_counter()-t0:.3f}s")

    # ── step 4 : timedelta → datetime.time conversion ────────
    t0 = _time.perf_counter()
    time_cols = table_config.get("time_cols", [])
    for col in time_cols:
        if col in df.columns:
            df[col] = (pd.Timestamp("1970-01-01") + df[col]).dt.time
    print(f"  step 4  timedelta fix          : {_time.perf_counter()-t0:.3f}s  ({len(time_cols)} col(s))")

    csv_path = None   # set in step 7, used for cleanup in finally

    # ── step 5 : DuckDB connection ────────────────────────────
    t0 = _time.perf_counter()
    duck_con = duckdb.connect(duckdb_path)
    print(f"  step 5  DuckDB connect         : {_time.perf_counter()-t0:.3f}s")

    try:
        # ── step 6 : DELETE existing rows ────────────────────
        t0 = _time.perf_counter()
        if date_col:
            duck_con.execute(
                f"DELETE FROM {table_name} WHERE {date_col} BETWEEN ? AND ?",
                [start_date, end_date],
            )
        else:
            duck_con.execute(f"DELETE FROM {table_name}")
        print(f"  step 6  DELETE existing rows   : {_time.perf_counter()-t0:.3f}s")

        # ── step 7 : write DataFrame to temp CSV ─────────────
        t0 = _time.perf_counter()
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".csv", mode="w")
        df.to_csv(tmp.name, index=False)
        tmp.close()
        csv_path = tmp.name
        print(f"  step 7  write temp CSV         : {_time.perf_counter()-t0:.3f}s")

        # ── step 8 : INSERT from CSV ──────────────────────────
        t0 = _time.perf_counter()
        duck_con.execute(f"INSERT INTO {table_name} SELECT * FROM read_csv('{csv_path}', all_varchar=true)")
        print(f"  step 8  INSERT from read_csv   : {_time.perf_counter()-t0:.3f}s")

        logger.info("load_table [%s] inserted %d rows", table_name, total_rows)
        print(f"  Inserted {total_rows:,} rows into DuckDB")

        # ── step 8b : CHECKPOINT to flush WAL and free dead rows ─
        t0 = _time.perf_counter()
        duck_con.execute("CHECKPOINT")
        print(f"  step 8b CHECKPOINT             : {_time.perf_counter()-t0:.3f}s")

    finally:
        # ── step 9 : close / flush + delete temp CSV ─────────
        t0 = _time.perf_counter()
        duck_con.close()
        if csv_path and os.path.exists(csv_path):
            os.unlink(csv_path)
        print(f"  step 9  DuckDB close/flush     : {_time.perf_counter()-t0:.3f}s")

    elapsed = _time.perf_counter() - t_total
    print(f"  ── TOTAL {elapsed:.3f}s  ({total_rows:,} rows)")
    return total_rows


def load_all_tables(tables: list, start_date: str = None, end_date: str = None, batch_days: int = LOAD_BATCH_DAYS, duckdb_path: str = DUCKDB_PATH) -> None:
    """Load data from MySQL into DuckDB for all configured tables, in day batches."""
    if not start_date or not end_date:
        start_date, end_date = _build_date_range(days_back=1)

    batches = list(_date_batches(start_date, end_date, batch_days))
    print(f"Date range: {start_date} -> {end_date}  ({len(batches)} batch(es) of {batch_days} day(s))")

    for cfg in tables:
        name  = cfg["mysql_table"]
        total = 0
        print(f"\nLoading: {name}")
        for b_start, b_end in batches:
            print(f"  Batch {b_start} -> {b_end}", end=" ... ", flush=True)
            try:
                n = load_table(cfg, b_start, b_end, duckdb_path)
                total += n
                print(f"{n:,} rows")
            except Exception as e:
                logger.error("load_table [%s] batch %s->%s FAILED: %s", name, b_start, b_end, e, exc_info=True)
                print(f"FAILED -> {e}")
        print(f"  Total: {total:,} rows inserted.")


# ─────────────────────────────────────────────────────────────
#  Cleanup
# ─────────────────────────────────────────────────────────────

def cleanup_old_data(tables: list, max_days: int = 30, duckdb_path: str = DUCKDB_PATH) -> None:
    """
    Delete rows older than max_days from tables that have cleanup=True.
    Tables with cleanup=False or date_col=None are skipped.
    """
    cutoff   = str(date.today() - timedelta(days=max_days))
    duck_con = duckdb.connect(duckdb_path)

    print(f"\n  Cleanup: removing rows older than {cutoff} (>{max_days} days)")
    try:
        for cfg in tables:
            table_name = cfg["mysql_table"]
            date_col   = cfg.get("date_col", "date")
            cleanup    = cfg.get("cleanup", True)

            if not cleanup or not date_col:
                print(f"  [SKIP] {table_name} — cleanup disabled or no date column.")
                continue

            duck_con.execute(f"DELETE FROM {table_name} WHERE {date_col} < ?", [cutoff])
            print(f"  Cleaned: {table_name}")
    finally:
        duck_con.close()
