# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
DB_CONFIG = {
    'host': '10.22.33.116',
    'user': 'root',
    'password': 'performance',
    'database': 'performanceroute'
}

# =============================================================================
# DATE LIMITS
# =============================================================================
MAX_DAYS_ALLOWED    = 30
MAX_SPECIFIC_DATES  = 10   # max individual dates in specific-dates mode
MAX_COMPARE_DAYS    = 7    # max days in compare mode
DEFAULT_DAYS        = 2

# =============================================================================
# CHART COLORS  (shared across all technologies and vendors)
# =============================================================================
CHART_COLORS = [
    "#3498db",  # Blue
    "#2ecc71",  # Green
    "#f39c12",  # Orange
    "#9b59b6",  # Purple
    "#1abc9c",  # Teal
]

# =============================================================================
# CELL LISTS
# =============================================================================

# --- Huawei 2G ---
_HUAWEI_2G_CLUSTER_1 = [
    'BAGOU1','BAGOU2','BAGOU3','BASSO1','BEROU1','BEROU2','BEROU3','BIRLA1',
    'BIRLA2','BOROD1','BOROD2','BOROD3','BRIGN2','DBAGOU1','DBAGOU3','DGOGOU1',
    'DGOGOU2','DONWA1','DONWA2','DONWA3','DPEHUN3','DSEKER2','DSEKER3','FOBOU3',
    'GAMIA1','GARAG2','GBASS1','GBASS2','GBASS3','GBEMO1','GBEMO2','GNAMB3','GNEMA2',
    'GOGO21','GOGO22','GOGOU1','GOGOU2','GOGOU3','GOUMO1','GUESSB1','GUESSB3','KABO1',
    'KABO2','KABO3','KAND21','KAND22','KAND23','KAND31','KAND33','KAND53','KANDI3',
    'KANWO1','KARIM3','KASSA3','KERO33','KEROU3','KOROD1','KOSSO1','KOSSO2','KOSSO3',
    'KOUTA1','KOUTA2','KOUTA3','LIBAN1','LIBAN2','LIBAN3','MAASS1','MAASS2','MALA41',
    'MALAN1','OUARA1','OUARA2','OUARA3','OUSON1','PAR291','PAR292','PAR293','PEHUN1',
    'PEHUN2','PEHUN3','PETIT1','PETIT2','PETIT3','PIAMI3','SAORE1','SEGBA1','SEGBA2',
    'SEKER2','SEKER3','SIKKI1','SIKKI2','SIKKI3','SINEN1','SINEN2','SINEN3','SOKOT2',
    'SORI1','SORI2','SORI3','SOUNO1','TCHAO2','TCHIC1','TCHIC2','TOBRE1','WARI1',
    'YAMPO2','ZOUGO1','ZOUGO2','ZOUGO3'
]

_HUAWEI_2G_CELL_29_MARCH = [
    'BASSO1','KOSSO3','KOUTA2','WARI1','GBASS2','GBASS1','KOSSO2','GBASS3','MALA41','GBEMO2','GOGO22','SINEN2','KABO3','PEHUN2','KABO2','KABO1','PAR293','GBEMO1','GNAMB3','PAR292','GUESSB1','PAR291','MAASS1','KEROU3','KOROD1','KOSSO1','YAMPO2','KAND53'
]

_ERICSSON_2G_10_MARS_1000Plus_Cell = [
    'ABOM21','ABOM22','ABOM23','ABOM41','ABOM42','ABOM43','ABOM61','ABOM62','ABOM63','ABOM91','ABOM92','ABOM93','ADAKP1','ADAKP2','ADAKP3','ADJAH1','ADJAH2','ADJAH3','ADJAO1','ADJAO2','ADJAO3','ADJAR1','ADJAR2','ADJAR3','ADJI1','ADJI2','ADJI3','ADJOH1','ADJOH2','ADJOH3','ADOH1','ADOH2','ADOH3','AFFAME1','AFFAME2','AFFAME3','AGAME1','AGAME2','AGAME3','AGAN1','AGAN2','AGAN3','AGASS1','AGASS2','AGASS3','AGBNO1','AGBNO2','AGBNO3','AGBOG1','AGBOG2','AGBOG3','AGBOK1','AGBOK2','AGBOK3','AGBOTA1','AGBOTA2','AGBOTA3','AGLAP1','AGLAP2','AGLAP3','AGONG1','AGONG2','AGONG3','AGONK1','AGONK2','AGONK3','AGOR21','AGOR22','AGOR23','AGOU21','AGOU22','AGOU23','AGOUA1','AGOUA2','AGOUA3','AGOUE1','AGOUE2','AGOUE3','AGOUNA1','AGOUNA2','AGOUNA3','AGUEG1','AGUEG2','AGUEG3','AHOZ21','AHOZ22','AHOZ23','AHOZO1','AHOZO2','AHOZO3','AITC21','AITC22','AITC23','AKAD21','AKAD22','AKAD23','AKAD31','AKAD32','AKAD33','AKAS21','AKAS22','AKAS23','AKAS51','AKAS52','AKAS53','AKAS61','AKAS62','AKAS63','AKASS1','AKASS2','AKASS3','AKIZA1','AKIZA2','AKIZA3','AKLAN1','AKLAN2','AKLAN3','AKODE1','AKODE2','AKODE3','AKOG21','AKOG22','AKOG23','ALAFI1','ALAFI2','ALAFI3','ALEDJ1','ALEDJ2','ALEDJ3','ALLA31','ALLA32','ALLA33','ALLAD1','ALLAD2','ALLAD21','ALLAD22','ALLAD23','ALLAD3','ANAN1','ANAN2','ANAN3','AORO1','AORO2','AORO3','APLAH1','APLAH2','APLAH3','ATCHO1','ATCHO2','ATCHO3','ATHIE1','ATHIE2','ATHIE3','ATOME1','ATOME2','ATOME3','ATRO21','ATRO22','ATRO23','ATRO31','ATRO32','ATRO33','ATTOGO1','ATTOGO2','ATTOGO3','AVAKP1','AVAKP2','AVAKP3','AVAM1','AVAM2','AVAM3','AYELA1','AYELA2','AYELA3','AYOM1','AYOM2','AYOM3','AYOU1','AYOU2','AYOU3','AZOHO1','AZOHO2','AZOHO3','AZOWL1','AZOWL2','AZOWL3','BANAME1','BANAME2','BANAME3','BANT21','BANT22','BANT23','BANTE1','BANTE2','BANTE3','BAREI1','BAREI2','BAREI3','BARIE1','BARIE2','BARIE3','BASSI1','BASSI2','BASSI3','BELL1','BELL2','BELL3','BEREC1','BEREC2','BEREC3','BETOUM1','BETOUM2','BETOUM3','BIRNI1','BIRNI2','BIRNI3','BOBE1','BOBE2','BOBE3','BODI1','BODI2','BODI3','BOH101','BOH102','BOH103','BOH131','BOH132','BOH133','BOH151','BOH152','BOH153','BOH161','BOH162','BOH163','BOHI111','BOHI112','BOHI113','BOHI31','BOHI32','BOHI33','BOHI91','BOHI92','BOHI93','BOHIC11','BOHIC12','BOHIC13','BONOU1','BONOU2','BONOU3','BOPA1','BOPA2','BOPA3','BOUGO1','BOUGO2','BOUGO3','BOUKO1','BOUKO2','BOUKO3','CAMPO1','CAMPO2','CAMPO3','CANA1','CANA2','CANA3','CASA1','CASA2','CASA3','CASSE1','CASSE2','CASSE3','CEB1','CEB2','CEB3','CENAG1','CENAG2','CENAG3','COBLI1','COBLI2','COBLI3','COCO11','COCO12','COCO13','COCOC1','COCOC2','COCOC3','COHOU1','COHOU2','COHOU3','COME1','COME2','COME3','COME31','COME32','COME33','COME41','COME42','COME43','COME51','COME52','COME53','COME71','COME72','COME73','COPAR1','COPAR2','COPAR3','COTIA1','COTIA2','COTIA3','COVE1','COVE2','COVE21','COVE22','COVE23','COVE3','DAGLAE1','DAGLAE2','DAGLAE3','DAGLAN1','DAGLAN2','DAGLAN3','DAGLAU1','DAGLAU2','DAGLAU3','DAGOUN1','DAGOUN2','DAKASS1','DAKASS2','DAKASS3','DAKODE1','DAKODE2','DALLA21','DALLA22','DALLAD1','DALLAD2','DALLAD3','DAN1','DAN2','DAN3','DANGB1','DANGB2','DANGB3','DANTO1','DANTO2','DANTO3','DASAR1','DASAR2','DASAR3','DASIL1','DASIL2','DASIL3','DASS11','DASS12','DASS13','DASS21','DASS22','DASS23','DASS31','DASS32','DASS33','DASS41','DASS42','DASS43','DATOR1','DATOR2','DATOR3','DATTOG1','DATTOG2','DATTOG3','DBETOU1','DBETOU2','DBOH111','DBOH112','DBOH113','DBOH151','DBOH152','DBOH153','DBOH161','DBOH162','DBOHI31','DBOHI32','DBOHI33','DBOHI91','DBOHI92','DBOHI93','DCOBLI2','DCOME21','DCOME52','DCOVE1','DCOVE2','DCOVE3','DDAN1','DDANT1','DDANT2','DDANT3','DDASS11','DDASS13','DDASS21','DDASS22','DDASS32','DDASS33','DDAVOZ1','DDAVOZ2','DDAVOZ3','DDJAKO1','DDJAKO2','DDJANG1','DDJANG2','DDJIDA2','DDJIDA3','DDJOU11','DDJOU12','DDJOU13','DDJOU22','DDJOU31','DDJOU32','DDJOU33','DDOGBO1','DDOGBO3','DDOKO1','DDOKO3','DEDOME1','DEDOME2','DEDOME3','DEGAU1','DEGAU2','DEGAU3','DEKOU1','DEKOU2','DEKOU3','DEKPO1','DEKPO2','DEKPO3','DENO1','DENO2','DENO3','DETOH1','DETOH2','DETOH3','DETOI1','DETOI2','DETOI3','DEVE1','DEVE2','DEVE3','DFIDJ11','DFIDJ12','DFIDJ13','DGLOD21','DGLOD22','DGLOD23','DGLODJ1','DGLODJ2','DGLODJ3','DGRAN23','DHOUEY3','DINDE1','DINDE2','DINDE3','DJABA1','DJABA2','DJABA3','DJAKO1','DJAKO2','DJAKO3','DJANE1','DJANE2','DJANE3','DJANG1','DJANG2','DJANG3','DJEFF1','DJEFF2','DJEFF3','DJEGB1','DJEGB2','DJEGB3','DJIDJ1','DJIDJ2','DJIDJ3','DJOH1','DJOH2','DJOH3','DJOT1','DJOT2','DJOT3','DJOU11','DJOU12','DJOU13','DJOU21','DJOU22','DJOU23','DJOU71','DJOU72','DJOU73','DJOU81','DJOU82','DJOU83','DJREG1','DJREG2','DJREG3','DKISSA1','DKISSA2','DKOUDO2','DKPADO1','DKPADO2','DKPADO3','DLOKO11','DLOKO12','DLOKO13','DLOKO21','DLOKO23','DLOKO41','DLOKO42','DLOKO43','DMBAR1','DMBAR2','DMBAR3','DNATI11','DNATI12','DNATI13','DOGB21','DOGB22','DOGB23','DOGBO1','DOGBO2','DOGBO3','DOKO1','DOKO2','DOKO3','DONA1','DONA2','DONA3','DOUAND1','DOUAND2','DOUAND3','DOUED21','DOUEDO1','DOWA1','DOWA2','DOWA3','DPATAR1','DSAVA32','DSAVA33','DSAVA41','DSAVA42','DSAVA43','DSAVAL1','DSAVAL2','DSE22','DSEGBO3','DSEHOU1','DSEME3','DSIMP13','DSITM11','DSITM12','DSITM13','DSITMO1','DSITMO2','DSITMO3','DSNOVI1','DSNOVI2','DSNOVI3','DSOCLO1','DSTOU1','DSTOU2','DSTOU3','DSUMA1','DSUMA2','DSUMA3','DTANGU1','DTANGU4','DTCHET1','DTOUI1','DTOUI2','DTOUI3','DTOVIK1','DWOLOG1','DWOLOG2','DZAGNA1','DZAGNA2','DZINVI1','DZINVI2','DZINVI3','DZOGBD2','EFFEO1','EFFEO2','EFFEO3','EKPE1','EKPE2','EKPE3','ETOI1','ETOI2','ETOI3','FAKA1','FAKA2','FAKA3','FIDJ21','FIDJ22','FIDJ23','FIFAD1','FIFAD2','FIFAD3','FIGNO1','FIGNO2','FIGNO3','FIROU1','FIROU2','FIROU3','GANH21','GANH22','GANH23','GANHI1','GANHI2','GANHI3','GAOUN1','GAOUN2','GAOUN3','GBADA1','GBADA2','GBADA3','GBANL1','GBANL2','GBANL3','GBEK1','GBEK2','GBEK3','GBETAG1','GBETAG2','GBETAG3','GBOZO1','GBOZO2','GBOZO3','GLAZ21','GLAZ22','GLAZ23','GLAZ31','GLAZ32','GLAZ33','GLOD21','GLOD22','GLOD23','GLOD31','GLOD32','GLOD33','GLODJ1','GLODJ2','GLODJ3','GOBAD1','GOBAD2','GOBAD3','GOBE1','GOBE2','GOBE3','GODO21','GODO22','GODO23','GODOG1','GODOG2','GODOG3','GODOM1','GODOM2','GODOM3','GOHOM1','GOHOM2','GOHOM3','GOUAN1','GOUAN2','GOUAN3','GOUKA1','GOUKA2','GOUKA3','GRAN21','GRAN22','GRAN23','GUILM1','GUILM2','GUILM3','HEKANM1','HEKANM2','HEKANM3','HEVI11','HEVI12','HEVI13','HEVI31','HEVI32','HEVI33','HEVI51','HEVI52','HEVI53','HEVIE21','HEVIE22','HEVIE23','HILAC1','HILAC2','HILAC3','HLAGB1','HLAGB2','HLAGB3','HLASS1','HLASS2','HLASS3','HLAZO1','HLAZO2','HLAZO3','HONVI1','HONVI2','HONVI3','HOUEY1','HOUEY2','HOUEY3','HOUN1','HOUN2','HOUN3','HOUNK1','HOUNK2','HOUNK3','IFANG1','IFANG2','IFANG3','IGBOD1','IGBOD2','IGBOD3','IGOLO1','IGOLO2','IGOLO3','IKPIN1','IKPIN2','IKPIN3','ITADJ1','ITADJ2','ITADJ3','IWOY1','IWOY2','IWOY3','JPII1','JPII2','JPII3','KABOU1','KABOU2','KABOU3','KALAV1','KALAV2','KALAV3','KANSO1','KANSO2','KANSO3','KAOBA1','KAOBA2','KAOBA3','KATAG1','KATAG2','KATAG3','KETO11','KETO12','KETO13','KETO21','KETO22','KETO23','KETO31','KETO32','KETO33','KISSA1','KISSA2','KISSA3','KLOUE1','KLOUE2','KLOUE3','KOKOR1','KOKOR2','KOKOR3','KOKOU1','KOKOU2','KOKOU3','KOLOK1','KOLOK2','KOLOK3','KOTOP1','KOTOP2','KOTOP3','KOUDO1','KOUDO2','KOUDO3','KOUNT1','KOUNT2','KOUNT3','KOUTY1','KOUTY3','KPANKO1','KPANKO2','KPANKO3','KPATA1','KPATA2','KPATA3','KPOMA1','KPOMA2','KPOMA3','KPOSE1','KPOSE2','KPOSE3','KPOTA1','KPOTA2','KPOTA3','KPOTO1','KPOTO2','KPOTO3','KRAKE1','KRAKE2','KRAKE3','LANT1','LANT2','LANT3','LENI21','LENI22','LENI23','LENIN1','LENIN2','LENIN3','LISSA1','LISSA2','LISSA3','LISSE1','LISSE2','LISSE3','LOBOG1','LOBOG2','LOBOG3','LOGOZ1','LOGOZ2','LOGOZ3','LOKO11','LOKO12','LOKO13','LOKO21','LOKO22','LOKO23','LOKO31','LOKO32','LOKO33','LOKO42','LOKOE1','LOKOE2','LOKOE3','LOKOG1','LOKOG2','LOKOG3','LOUWO1','LOUWO2','LOUWO3','MADJ1','MADJ2','MADJ3','MAKI21','MAKI22','MAKI23','MALAH1','MALAH2','MALAH3','MANIG1','MANIG2','MANIG3','MANSO1','MANSO2','MANSO3','MANTA1','MANTA2','MANTA3','MASSE1','MASSE2','MASSE3','MASSI1','MASSI2','MASSI3','MEDED1','MEDED2','MEDED3','MONK1','MONK2','MONK3','MOOVH1','MOOVH2','MOOVH3','MOUGNO1','MOUGNO2','MOUGNO3','NASSO1','NASSO2','NASSO3','NATI11','NATI12','NATI13','NATI21','NATI22','NATI23','NATI31','NATI32','NATI33','NATI41','NATI42','NATI43','NATI51','NATI52','NATI53','NATI61','NATI62','NATI63','NATI71','NATI72','NATI73','NDAHON1','NDAHON2','NDAHON3','ONIG21','ONIG22','ONIG23','ONIGBL1','ONIGBL2','ONIGBL3','ONKLO1','ONKLO2','ONKLO3','OROUK1','OROUK2','OROUK3','OTTO1','OTTO2','OTTO3','OUAKE1','OUAKE2','OUAKE3','OUEAD1','OUEAD2','OUEAD3','OUED21','OUED22','OUED23','OUEDE1','OUEDE2','OUEDE3','OUEDO1','OUEDO2','OUEDO3','OUEOE1','OUEOE2','OUEOE3','OUESS1','OUESS2','OUESS3','OUID11','OUID12','OUID13','OUID14','OUID21','OUID22','OUID23','OUINH1','OUINH2','OUINH3','OUOGH1','OUOGH2','OUOGH3','OWODE1','OWODE2','OWODE3','PAHO41','PAHO42','PAHO43','PAHO51','PAHO52','PAHO53','PAOUI1','PAOUI2','PAOUI3','PAPAR1','PAPAR2','PAPAR3','PARN11','PARN12','PARN13','PARN21','PARN22','PARN23','PATAR1','PATAR2','PATAR3','PELEB1','PELEB2','PELEB3','PENES1','PENES2','PENES3','PERMA1','PERMA2','PERMA3','PIRA1','PIRA2','PIRA3','PK31','PK32','PK33','PK91','PK92','PK93','POBE21','POBE22','POBE23','PORGA1','PORGA2','PORGA3','POSSO1','POSSO2','POSSO3','PREKE1','PREKE2','PREKE3','ROUDPE1','ROUDPE2','ROUDPE3','SACLO1','SACLO2','SACLO3','SAKET1','SAKET2','SAKET3','SAVA21','SAVA22','SAVA23','SAVA31','SAVAL1','SAVAL2','SAVAL3','SAVE21','SAVE22','SAVE23','SAVE31','SAVE32','SAVE33','SAVI1','SAVI2','SAVI3','SE21','SE22','SE23','SEDJED1','SEDJED2','SEDJED3','SEGBO1','SEGBO2','SEGBO3','SEHOU1','SEHOU2','SEHOU3','SEKAN1','SEKAN2','SEKAN3','SEME1','SEME2','SEME3','SEMER1','SEMER2','SEMER3','SETTO1','SETTO2','SETTO3','SEY11','SEY12','SEY13','SIKEC1','SIKEC2','SIKEC3','SOCLO1','SOCLO2','SOCLO3','SOKPO1','SOKPO2','SOKPO3','SOS1','SOS2','SOS3','SUCOB1','SUCOB2','SUCOB3','TAKON1','TAKON2','TAKON3','TANGU1','TANGU2','TANGU3','TANK21','TANK22','TANK23','TCHET1','TCHET2','TCHET3','TCHETO1','TCHETO2','TCHETO3','TCHIN1','TCHIN2','TCHIN3','TIND21','TIND22','TIND23','TOGB21','TOGB22','TOGB23','TOGBA1','TOGBA2','TOGBA3','TOGO11','TOGO12','TOGO13','TOGO21','TOGO22','TOGO23','TOHOUE1','TOHOUE2','TOHOUE3','TOKO1','TOKO2','TOKO3','TOKPD1','TOKPD2','TOKPD3','TONAT1','TONAT2','TONAT3','TORIB1','TORIB2','TORIB3','TORICA1','TORICA2','TORICA3','TOUCO1','TOUCO2','TOUCO3','TOUI1','TOUI2','TOUI3','TOVIK1','TOVIK2','TOVIK3','TOWE1','TOWE2','TOWE3','TRIPO1','TRIPO2','TRIPO3','VAKON2','VAKON3','VANH1','VANH2','VANH3','YAOUI1','YAOUI2','YAOUI3','YOKO1','YOKO2','YOKO3','ZAGNA1','ZAGNA2','ZAGNA3','ZAHLA1','ZAHLA2','ZAHLA3','ZAKPO1','ZAKPO2','ZAKPO3','ZALI1','ZALI2','ZALI3','ZE1','ZE2','ZE3','ZINVI1','ZINVI2','ZINVI3','ZOGB11','ZOGB12','ZOGB13','ZOGB21','ZOGB22','ZOGB23','ZOGB41','ZOGB42','ZOGB43','ZOGBD1','ZOGBD2','ZOGBD3','ZOGBO1','ZOGBO2','ZOGBO3','ZONG31','ZONG32','ZONG33','ZOUKO1','ZOUKO2','ZOUKO3','ZOUN1','ZOUN2','ZOUN3','ZOUNO1','ZOUNO2','ZOUNO3','ZOUZO1','ZOUZO2','ZOUZO3','HOUEY21','HOUEY22','HOUEY23','DODJB3','DODJB2','DODJB1','AGLOG3','AGLOG2','AGLOG1','HEHOU3','HEHOU2','HEHOU1','DJAVI3','DJAVI2','DJAVI1','AGAS23','AGAS22','AGAS21','GBEDJ3','GBEDJ2','GBEDJ1','DJEF23','DJEF22','DJEF21','VAKO23','VAKO22','VAKO21','WESTA3','HOUND1','WESTA1','HOUND3','HOUND2','WESTA2','ADOUK2','ADOUK1','ADOUK3','DJOU63','DJOU62','DJOU61','DJOU53','DJOU52','DJOU51','BASS23','BASS22','BASS21'
]

_ERICSSON_2G_LAC_TAC_CLUSTER_1 = [
    'AGLOG1','AGLOG2','AGLOG3','AGOUNA1','AGOUNA2','AGOUNA3','DAGOUN1','DAGOUN2',
    'AKOUN1','AKOUN2','AKOUN3','ALAFI1','ALAFI2','ALAFI3','BODJE1','BODJE2','BODJE3',
    'CANA1','CANA2','CANA3','COME1','COME2','COME3','COME21','COME22','COME23',
    'DCOME21','COME31','COME32','COME33','COME41','COME42','COME43','COME51','COME52',
    'COME53','DCOME52','COME61','COME62','COME63','COME71','COME72','COME73','COME81',
    'COME82','COME83','COME91','COME92','COME93','DDOGBO1','DDOGBO3','DOGBO1','DOGBO2',
    'DOGBO3','DOGB21','DOGB22','DOGB23','GOBAD1','GOBAD2','GOBAD3','GOGOR1','GOGOR2',
    'GOGOR3','HELOT1','HELOT2','HELOT3','HLAGB1','HLAGB2','HLAGB3','KABOU1','KABOU2',
    'KABOU3','DKANDI1','DKANDI2','DKANDI3','KANDI1','KANDI2','KANDI3','KASSOU1',
    'KASSOU2','KASSOU3','DKISSA1','DKISSA2','KISSA1','KISSA2','KISSA3','KOUMA1',
    'KOUMA3','KOUMA2','LOKO81','LOKO82','LOKO83','LOKO93','LOKO91','LOKO92','MALAN1',
    'MALAN2','MALAN3','DMALA21','DMALA22','DMALA23','MALA21','MALA22','MALA23','MALA31',
    'MALA32','MALA33','MALA41','MALA42','MALA43','MALA51','MALA52','MALA53','MALA61',
    'MALA62','MALA63','MALAH1','MALAH2','MALAH3','MASSI1','MASSI2','MASSI3','NAT121',
    'NAT122','NAT123','NATI51','NATI52','NATI53','NDAHON1','NDAHON2','NDAHON3','PAPAN1',
    'PAPAN2','PAPAN3','SOKPO1','SOKPO2','SOKPO3','SONTA1','SONTA2','SONTA3','TCHAO1',
    'TCHAO2','TCHAO3','TCHA21','TCHA22','TCHA23','THIO1','THIO2','THIO3','YAMBO1',
    'YAMBO2','YAMBO3','ZALI1','ZALI2','ZALI3'
]

_ERICSSON_3G_CLUSTER_1 = [
'UAGLOG7','UAGLOG8','UAGLOG9','UAGOUN7','UAGOUN8','UAGOUN9','UAKOUN7','UAKOUN8','UAKOUN9','UALAFI7','UALAFI8','UALAFI9','UBODJE7','UBODJE8','UBODJE9','UCANA7','UCANA8','UCANA9','UCOME7','UCOME8','UCOME9','UCOME27','UCOME28','UCOME29','UCOME37','UCOME38','UCOME39','UCOME47','UCOME48','UCOME49','UCOME57','UCOME58','UCOME59','UCOME67','UCOME68','UCOME69','UCOME77','UCOME78','UCOME79','UCOME87','UCOME88','UCOME89','UCOME97','UCOME98','UCOME99','UDOGBO7','UDOGBO8','UDOGBO9','UDOGB27','UDOGB28','UDOGB29','UGOBAD7','UGOBAD8','UGOBAD9','UGOGOR7','UGOGOR8','UGOGOR9','UHELOT7','UHELOT8','UHELOT9','UHLAGB7','UHLAGB8','UHLAGB9','UKABOU7','UKABOU8','UKABOU9','UKANDI7','UKANDI8','UKANDI9','UKASSO7','UKASSO8','UKASSO9','UKISSA7','UKISSA8','UKISSA9','UKOUMA7','UKOUMA8','UKOUMA9','ULOKO87','ULOKO88','ULOKO89','ULOKO97','ULOKO98','ULOKO99','UMALAN7','UMALAN8','UMALAN9','UMALA27','UMALA28','UMALA29','UMALA37','UMALA38','UMALA39','UMALA47','UMALA48','UMALA49','UMALA57','UMALA58','UMALA59','UMALA67','UMALA68','UMALA69','UMALAH7','UMALAH8','UMALAH9','UMASSI7','UMASSI8','UMASSI9','UNAT127','UNAT128','UNAT129','UNATI57','UNATI58','UNATI59','UNDAHO7','UNDAHO8','UNDAHO9','UPAPAN7','UPAPAN8','UPAPAN9','USOKPO7','USOKPO8','USOKPO9','USONTA7','USONTA8','USONTA9','UTCHAO7','UTCHAO8','UTCHAO9','UTCHA27','UTCHA28','UTCHA29','UTHIO7','UTHIO8','UTHIO9','UYAMBO7','UYAMBO8','UYAMBO9','UZALI17','UZALI18','UZALI19'
]

_ERICSSON_4G_CLUSTER_1 = [
'LAGLOGB1','LAGLOGB2','LAGLOGB3','LAGLOGB4','LAGLOGB5','LAGLOGB6','LAGOUN1','LAGOUN2','LAGOUN3','LAKOUN1','LAKOUN2','LAKOUN3','LALAFI1','LALAFI2','LALAFI3','LBODJE1','LBODJE2','LBODJE3','LBODJE4','LBODJE5','LBODJE6','LBODJE7','LBODJE8','LBODJE9','LCANA1','LCANA2','LCANA3','LCOME1','LCOME2','LCOME3','LCOME4','LCOME5','LCOME6','LCOME21','LCOME22','LCOME23','LCOME24','LCOME25','LCOME26','LCOME31','LCOME32','LCOME33','LCOME34','LCOME35','LCOME36','LCOME41','LCOME42','LCOME43','LCOME44','LCOME45','LCOME46','LCOME51','LCOME52','LCOME53','LCOME54','LCOME55','LCOME56','LCOME61','LCOME62','LCOME63','LCOME64','LCOME65','LCOME66','LCOME71','LCOME72','LCOME73','LCOME81','LCOME82','LCOME83','LCOME87','LCOME88','LCOME89','LCOME8A','LCOME8B','LCOME8C','LCOME91','LCOME92','LCOME93','LCOME94','LCOME95','LCOME96','LCOME97','LCOME98','LCOME99','LCOME9A','LCOME9B','LCOME9C','LDOGBO1','LDOGBO2','LDOGBO3','LDOGBO7','LDOGBO8','LDOGBO9','LDOGBOA','LDOGBOB','LDOGBOC','LDOGB21','LDOGB22','LDOGB23','LDOGB27','LDOGB28','LDOGB29','LDOGB2A','LDOGB2B','LDOGB2C','LGOBAD1','LGOBAD2','LGOBAD3','LGOGOR1','LGOGOR2','LGOGOR3','LHELOT1','LHELOT2','LHELOT3','LHLAGB1','LHLAGB2','LHLAGB3','LKABOU1','LKABOU2','LKABOU3','LKANDI1','LKANDI2','LKANDI3','LKANDI4','LKANDI5','LKANDI6','LKANDI7','LKANDI8','LKANDI9','LKANDIA','LKANDIB','LKANDIC','LKASSO1','LKASSO2','LKASSO3','LKASSO4','LKASSO5','LKASSO6','LKASSO7','LKASSO8','LKASSO9','LKISSA1','LKISSA2','LKISSA3','LKISSA7','LKISSA8','LKISSA9','LKISSAA','LKISSAB','LKISSAC','LKOUMA1','LKOUMA2','LKOUMA3','LKOUMA7','LKOUMA8','LKOUMA9','LLOKO81','LLOKO82','LLOKO83','LLOKO91','LLOKO92','LLOKO93','LLOKO94','LLOKO95','LLOKO96','LLOKO97','LLOKO98','LLOKO99','LLOKO9A','LLOKO9B','LLOKO9C','LMALAN1','LMALAN2','LMALAN3','LMALAN4','LMALAN5','LMALAN6','LMALAN7','LMALAN8','LMALAN9','LMALANA','LMALANB','LMALANC','LMALA21','LMALA22','LMALA23','LMALA24','LMALA25','LMALA26','LMALA87','LMALA88','LMALA89','LMALA2A','LMALA2B','LMALA2C','LMALA31','LMALA32','LMALA33','LMALA34','LMALA35','LMALA36','LMALA37','LMALA38','LMALA39','LMALA41','LMALA42','LMALA43','LMALA47','LMALA48','LMALA49','LMALA51','LMALA52','LMALA53','LMALA57','LMALA58','LMALA59','LMALA61','LMALA62','LMALA63','LMALA67','LMALA68','LMALA69','LMALAH1','LMALAH2','LMALAH3','LMASSI1','LMASSI2','LMASSI3','LNAT121','LNAT122','LNAT123','LNAT127','LNAT128','LNAT129','LNAT12A','LNAT12B','LNAT12C','LNATI51','LNATI52','LNATI53','LNATI54','LNATI55','LNATI56','LNDAHO1','LNDAHO2','LNDAHO3','LPAPAN1','LPAPAN2','LPAPAN3','LPAPAN4','LPAPAN5','LPAPAN6','LPAPAN7','LPAPAN8','LSOKPO1','LSOKPO2','LSOKPO3','LSONTA1','LSONTA2','LSONTA3','LTCHAO1','LTCHAO2','LTCHAO3','LTCHAO4','LTCHAO5','LTCHAO6','LTCHAO7','LTCHAO8','LTCHAO9','LTCHAOA','LTCHAOB','LTCHAOC','LTCHA21','LTCHA22','LTCHA23','LTCHA24','LTCHA25','LTCHA26','LTCHA87','LTCHA88','LTCHA89','LTCHA2A','LTCHA2B','LTCHA2C','LTHIO1','LTHIO2','LTHIO3','LYAMBO1','LYAMBO2','LYAMBO3','LZALI11','LZALI12','LZALI13'
]

_HUAWEI_2G_CLUSTER_2 = [
    'KAND53','GOROG1','KASSA3','PAR291','LIBAN3','GBEMO2','PAR292','SORI2','BOROD1',
    'SORI1','SORI3','PAR293','DONWA2','KAND21','OUARA2','BASSO1','OUARA1','SOKOT2',
    'PETIT1','KAND22','GOGOU3','OUARA3','BEROU2','BAGOU3','BEROU1','BEROU3','BOROD3',
    'GOGO22','BAGOU2','SEKER3','BAGOU1','BOROD2','GOGOU1','KAND33','ZOUGO2','SEGBA1',
    'SINEN3','SINEN2','PETIT2','KOUTA2','ZOUGO1','KOSSO3','WARI1','GOGOU2','DBAGOU3',
    'SINEN1','KABO3','KANWO1','GUESSB1','KANDI3','SEGBA2','PEHUN1','KAND43','PETIT3',
    'ZOUGO3','PEHUN2','SEKER2','GARAG2','KOROD1','MAASS1','DSEKER2','OUSON1','GBEMO1',
    'LIBAN1','SEKER1','DBAGOU1','KOSSO2','TOBRE1','DGOGOU2','KOUTA3','GBASS2','PAR511',
    'YAMPO2','DSEKER3','KIKAES3','GNAMB3','DGOGOU1','SIKKI1','KAND93','KAND23','PEHUN3',
    'GAMIA1','GUESSB3','SAORE1','KABO1','KAND31','KAND92','GOGO21','SIKKI2','KABO2',
    'PAR313','FOBOU3','SAORE2','SIKKI3','GOGO23','GNEMA3','SAKAB1','DPEHUN3','GNEMA2',
    'DONWA3','KEROU3','GUESSB2','GBASS3','DPEHUN1','GBASS1','GNEMA1','FOBOU2','LIBAN2',
    'MALA41','SAORE3','PAR512','TOBRE2','DGOGOU3','TOBRE3','KOUTA1','BORI2','DSEKER1',
    'BRIGN2','BERKO1','SOUBO1','FOBOU1','PAR513','GAMIA2','TCHAO2','DPEHUN2','DIADI3',
    'PAR423','GUESS3','THYA1','KPEBO2','GOMME1','GANRU1','TCHAO1','KAKOU1','TCHIC1',
    'BANIT3','PAR422','BODJE3','GOUMO1','BOUKA2','DONWA1','PAR122','DGAMIA1','KAKIK1',
    'TCHA22','KOMIG3','BOUKA1','PAR462','KIKAES2','KERO33','PAR311','BOUAN2','GBEI1',
    'BORI1','KAND82','SANDI1','BEMBE1','KOMIG1','PAR501','DOUGO1'
]


_ERICSSON_2G_SD_TOP30_WORST_CELL =[
    'KABOU2','KABOU1','ONKLO1','ALAFI1','OWOLA1','GOGOR2','TECTI1','KOKOR2','BILKO3','OKEOW2','OWOLA3','SAVE53','TOKO2','POBE3','OUAKE2','MANI22','AGBAD1','AFLAN2','ZAGNA1','SEHOU2','TOWE3','NIEKE2','KILIB2','TOUI2','KEDEK2','DJOU62','FIROU2','NATI21','BIGUI2','BIGUI3'
]

# _HUAWEI_2G_TAC_LAC_SECOND_BATCH =[
#     'ANGAR1','ANGAR2','ANGAR3','ARBON1','ARBON2','ARBON3','BANGO1','BANGO2','BANGO3','BEROU1','BEROU2','BEROU3','BOROD1','BOROD2','BOROD3','DERAC1','DERAC2','DERAC3','FOBOK1','FOBOK2','FOBOK3','DFOUNO1','DFOUNO2','DFOUNO3','FOUNO1','FOUNO2','FOUNO3','GANRO1','GANRO2','GANRO3','GBEKU1','GBEKU2','GBEKU3','GBERO1','GBERO2','GBERO3','DGOGOU1','DGOGOU2','DGOGOU3','GOGOU1','GOGOU2','GOGOU3','GUESSB1','GUESSB2','GUESSB3','KABO1','KABO2','KABO3','DKEROU2','DKEROU3','KEROU1','KEROU2','KEROU3','KOMPA1','KOMPA2','KOMPA3','KOUTA1','KOUTA2','KOUTA3','LIBOU1','LIBOU2','LIBOU3','MOLLA1','MOLLA2','MOLLA3','OLOUGB1','OLOUGB2','OLOUGB3','OUARA1','OUARA2','OUARA3','PAR171','PAR172','PAR173','DPEHUN1','DPEHUN2','DPEHUN3','PEHUN1','PEHUN2','PEHUN3','PETIT1','PETIT2','PETIT3','SAHAD1','SAHAD2','SAHAD3','DSERA1','DSERA2','SERAR1','SERAR2','SERAR3','SIKKI1','SIKKI2','SIKKI3','SOKOT1','SOKOT2','SOKOT3','SONNO1','SONNO2','SONNO3','SONTO1','SONTO2','SONTO3','TOBRE1','TOBRE2','TOBRE3','WOBAD1','WOBAD2','WOBAD3','WORIA1','WORIA2','WORIA3'
# ]

_HUAWEI_2G_TAC_LAC_SECOND_BATCH =[
    'ANGAR1','ANGAR2','ANGAR3','ARBON1','ARBON2','ARBON3','BAGOU1','BAGOU2','BAGOU3','DBAGOU1','DBAGOU3','BANGO1','BANGO2','BANGO3','BERKO1','BERKO2','BERKO3','BEROU1','BEROU2','BEROU3','BOROD1','BOROD2','BOROD3','DERAC1','DERAC2','DERAC3','FOBOK1','FOBOK2','FOBOK3','DFOUNO1','DFOUNO2','DFOUNO3','FOUNO1','FOUNO2','FOUNO3','GANRO1','GANRO2','GANRO3','GBASS1','GBASS2','GBASS3','GBEKU1','GBEKU2','GBEKU3','GBERO1','GBERO2','GBERO3','DGOGOU1','DGOGOU2','DGOGOU3','GOGOU1','GOGOU2','GOGOU3','GUESSB1','GUESSB2','GUESSB3','KABO1','KABO2','KABO3','DKEROU2','DKEROU3','KEROU1','KEROU2','KEROU3','KOMPA1','KOMPA2','KOMPA3','KOSSO1','KOSSO2','KOSSO3','KOUTA1','KOUTA2','KOUTA3','DLIBA3','LIBAN1','LIBAN2','LIBAN3','LIBOU1','LIBOU2','LIBOU3','LOUG21','LOUG22','LOUG23','MOLLA1','MOLLA2','MOLLA3','OLOUGB1','OLOUGB2','OLOUGB3','OUARA1','OUARA2','OUARA3','PAR171','PAR172','PAR173','DPEHUN1','DPEHUN2','DPEHUN3','PEHUN1','PEHUN2','PEHUN3','PETIT1','PETIT2','PETIT3','SAHAD1','SAHAD2','SAHAD3','SAORE1','SAORE2','SAORE3','DSERA1','DSERA2','SERAR1','SERAR2','SERAR3','SIKKI1','SIKKI2','SIKKI3','SOKOT1','SOKOT2','SOKOT3','SONNO1','SONNO2','SONNO3','SONTO1','SONTO2','SONTO3','TANKO1','TANKO2','TANKO3','TOBRE1','TOBRE2','TOBRE3','WOBAD1','WOBAD2','WOBAD3','WORIA1','WORIA2','WORIA3','YARA1','YARA2','YARA3'
]

##



_ERICSSON_2G_ACTION_27_MARCH_2_SITE =[
    'KOUAT1','KOUAT2','KOUAT3','TCHAG1','TCHAG2','TCHAG3'
]

# --- Ericsson 2G ---
# Add batches when ready:
# _ERICSSON_2G_ZONE_NORTH = ['CELL1', ...]

# --- Ericsson 3G ---
# Add batches when ready:
# _ERICSSON_3G_ZONE_NORTH = ['CELL1', ...]

# --- Ericsson 4G ---
# Add batches when ready:
# _ERICSSON_4G_ZONE_NORTH = ['CELL1', ...]

# =============================================================================
# TECHNOLOGIES
#
# Structure:
#   TECHNOLOGIES[tech_key] = {
#       "label":   str,            # shown in the UI tab
#       "vendors": {
#           vendor_key: {
#               "label":    str,   # shown in vendor button
#               "sql_file": str,   # filename in SQL/ directory
#               "date_col": str,   # column ref used in WHERE date filter
#               "time_col": str,   # column ref injected for hourly select/group
#               "cell_col": str,   # column ref used in WHERE cell filter
#               "kpi_groups": {
#                   "Chart Title": {"columns": ["COL_ALIAS"], "threshold": N|None}
#               },
#               "batches": {
#                   "batch_key": {"label": "Display Name", "cells": [...]}
#               }
#           }
#       }
#   }
#
# Batch "all" is always added automatically — do NOT define it here.
# =============================================================================

TECHNOLOGIES = {

    # =========================================================================
    # 2G
    # =========================================================================
    "2g": {
        "label": "2G",
        "vendors": {

            # -----------------------------------------------------------------
            # Ericsson 2G
            # -----------------------------------------------------------------
            "ericsson": {
                "label"    : "Ericsson",
                "sql_file" : "ericsson_2g.sql",
                "date_col" : "e.DATE",
                "time_col" : "e.TIME",
                "cell_col" : "e.CELL_NAME",

                "kpi_groups": {
                    "2G CSSR (%)": {
                        "columns": ["CSSR_ERICSSON"],
                        "threshold": 99
                    },
                    "2G CDR (%)": {
                        "columns": ["CDR_ERICSSON"],
                        "threshold": 1
                    },
                    "2G CBR (%)": {
                        "columns": ["CBR_ERICSSON"],
                        "threshold": 1
                    },
                    "2G Cell Availability Rate (%)": {
                        "columns": ["CELL_AVAILABILITY_RATE_ERICSSON"],
                        "threshold": 99
                    },
                    "2G TCH Availability Rate (%)": {
                        "columns": ["TCH_AVAILABILITY_RATE_ERICSSON"],
                        "threshold": None
                    },
                    "2G TCH Congestion Rate (%)": {
                        "columns": ["TCH_CONGESTION_RATE_ERICSSON"],
                        "threshold": None
                    },
                    "2G SDCCH Drop Rate (%)": {
                        "columns": ["SDCCH_DROP_RATE_ERICSSON"],
                        "threshold": None
                    },
                    "2G SDCCH Blocking Rate (%)": {
                        "columns": ["SDCCH_BLOCKING_RATE_ERICSSON"],
                        "threshold": None
                    },
                    "2G SDCCH Congestion Rate (%)": {
                        "columns": ["SDCCH_CONGESTION_RATE_ERICSSON"],
                        "threshold": None
                    },
                    "2G SDCCH Traffic (Erlang)": {
                        "columns": ["SDCCH_TRAFFIC_ERICSSON"],
                        "threshold": None
                    },
                    "2G Downtime Manual": {
                        "columns": ["DOWNTIME_MANUAL"],
                        "threshold": None
                    },
                    "2G Traffic Data (GB)": {
                        "columns": ["TRAFFIC_DATA_GB_ERICSSON"],
                        "threshold": None
                    },
                    "2G Traffic Voice": {
                        "columns": ["TRAFFIC_VOIX_ERICSSON"],
                        "threshold": None
                    },
                },

                # Add batches here when ready:
                # "zone_north": {"label": "North Zone", "cells": _ERICSSON_2G_ZONE_NORTH},
                "batches": {
                     "cluster_1": {
                        "label": "LAC TAC CHANGE",
                        "cells": _ERICSSON_2G_LAC_TAC_CLUSTER_1,
                    },
                     "cluster_2": {
                        "label": "ERICSSON 1000 Plus Cell Improvement ",
                        "cells": _ERICSSON_2G_10_MARS_1000Plus_Cell,
                    },
                     "cluster_3": {
                        "label": "ERICSSON_2G_SD_TOP30_WORST_CELL",
                        "cells": _ERICSSON_2G_SD_TOP30_WORST_CELL,
                    },
                    "cluster_4": {
                        "label": "_ERICSSON_2G_ACTION_27_MARCH_2_SITE",
                        "cells": _ERICSSON_2G_ACTION_27_MARCH_2_SITE,
                    },
                     "cluster_5": {
                        "label": "_ERICSSON_2G_LAC_TAC_BATCH2",
                        "cells": ['ADJID1','ADJID2','ADJID3','ADJI1','ADJI2','ADJI3','AFLAN1','AFLAN2','AFLAN3','AHITO1','AHITO2','AHITO3','AHOME1','AHOME2','AHOME3','AVOGB1','AVOGB2','AVOGB3','AZOV31','AZOV32','AZOV33','BOH161','BOH162','BOH163','DBOH161','DBOH162','DAN1','DAN2','DAN3','DDAN1','DDJAKO1','DDJAKO2','DJAKO1','DJAKO2','DJAKO3','DOHOU1','DOHOU2','DOHOU3','DOME1','DOME2','DOME3','DONTA1','DONTA2','DONTA3','DOUME1','DOUME2','DOUME3','FONPA1','FONPA2','FONPA3','FONKP1','FONKP2','FONKP3','HLASS1','HLASS2','HLASS3','HOUN1','HOUN2','HOUN3','KOHOU1','KOHOU2','KOHOU3','KOUSS1','KOUSS2','KOUSS3','KPAKP1','KPAKP2','KPAKP3','KPOBA1','KPOBA2','KPOBA3','KPOZO1','KPOZO2','KPOZO3','LAGBA1','LAGBA2','LAGBA3','LEGO1','LEGO2','LEGO3','MANSO1','MANSO2','MANSO3','MASSA1','MASSA2','MASSA3','MONK1','MONK2','MONK3','OUANS1','OUANS2','OUANS3','SETTO1','SETTO2','SETTO3','TANVE1','TANVE2','TANVE3','TCHAK1','TCHAK2','TCHAK3','TIND21','TIND22','TIND23','YAGBA1','YAGBA2','YAGBA3','ZATAN1','ZATAN2','ZATAN3','ZAHLA1','ZAHLA2','ZAHLA3','ZOUN1','ZOUN2','ZOUN3'],
                    },
                     "cluster_6": {
                        "label": "_ERICSSON_CONGESTION_ACTION",
                        "cells": ['KOUAT1','ABOM42','AHOU3','AHOU3','AHOZ21','ALLAD21','ALLAD22','ATRO33','ATROP3','AVOGB1','AZOV22','COVE31','COVE31','DAZOV22','DRE1','HOUN1','HOUN2','HOUN2','IDIGN1','KET102','KETO13','KETO33','KETO63','KOUAN3','KPOTO1','KPOTO2','KPOZO3','NIARS1','NIARS1','ODOME1','ODOME1','OUES21','ZAKAN1'],
                    },#
                      "cluster_7": {
                        "label": "_ERICSSON_2G_TO_3G_CELL_ACTION",
                        "cells": ['PERMA1','TCHAG2','AFFES1','KOUAN2','ONKLO1','YAKAB3','PATAR2','DEDOME3','TANG22','FOMON3','KEDEK1','DANTO1','DONDJ1','AFLAN2','ALLAD23','DANTO3','GOUNT1','KOLOK2','MANI22','OUEDE1','SUCOB1','BIRNI3','OUESS1','GOUAN2','ANAN1','OUEOE3','ANAN3','KPOSE2','AGBAD1','PINGO1'],
                    },
                      "cluster_8": {
                        "label": "_ERICSSON_PKBSC06_FIRST_BATCH_V2",
                        "cells": ['AFFES1','AFFES2','AFFES3','AGBAD1','AGBAD2','AGBAD3','AGOUA1','AGOUA2','AGOUA3','AKLAN1','AKLAN2','AKLAN3','ALAFI1','ALAFI2','ALAFI3','ALEDJ1','ALEDJ2','ALEDJ3','ANAN1','ANAN2','ANAN3','ANOUM1','ANOUM2','ANOUM3','AORO1','AORO2','AORO3','ASSANT1','ASSANT2','ASSANT3','AZRAO1','AZRAO2','AZRAO3','BADJO1','BADJO2','BADJO3','BAKOU1','BAKOU2','BAKOU3','BANTE1','BANTE2','BANTE3','BANT21','BANT22','BANT23','BAREI1','BAREI2','BAREI3','BARIE1','BARIE2','BARIE3','BASSI1','BASSI2','BASSI3','BASS21','BASS22','BASS23','BAYAK1','BAYAK2','BAYAK3','BELL1','BELL2','BELL3','BEREC1','BEREC2','BEREC3','BERE21','BERE22','BERE23','BIGUI1','BIGUI2','BIGUI3','BILKO1','BILKO2','BILKO3','BIRNI1','BIRNI2','BIRNI3','BOBE1','BOBE2','BOBE3','BODI1','BODI2','BODI3','BONGO1','BONGO2','BONGO3','BOUGO1','BOUGO2','BOUGO3','BOUKO1','BOUKO2','BOUKO3','CHABI1','CHABI2','CHABI3','COBLI1','COBLI2','COBLI3','DCOBLI2','COPAR1','COPAR2','COPAR3','COTIA1','COTIA2','COTIA3','DARIN1','DARIN2','DARIN3','DASAR1','DASAR2','DASAR3','DATOR1','DATOR2','DATOR3','DJEGB1','DJEGB2','DJEGB3','DDJOU11','DDJOU12','DDJOU13','DJOU11','DJOU12','DJOU13','DJO101','DJO102','DJO103','DDJOU22','DJOU21','DJOU22','DJOU23','DDJOU31','DDJOU32','DDJOU33','DJOU41','DJOU42','DJOU43','DJOU51','DJOU52','DJOU53','DJOU61','DJOU62','DJOU63','DJOU71','DJOU72','DJOU73','DJOU81','DJOU82','DJOU83','DJOU91','DJOU92','DJOU93','DOGUE1','DOGUE2','DOGUE3','FAKA1','FAKA2','FAKA3','FIROU1','FIROU2','FIROU3','FOTEN1','FOTEN2','FOTEN3','FOMON1','FOMON2','FOMON3','GAOUN1','GAOUN2','GAOUN3','GBANL1','GBANL2','GBANL3','GLAZ11','GLAZ12','GLAZ13','GLAZ21','GLAZ22','GLAZ23','GLAZ31','GLAZ32','GLAZ33','GLAZ41','GLAZ42','GLAZ43','GOBE1','GOBE2','GOBE3','GOGOR1','GOGOR2','GOGOR3','GORFI1','GORFI2','GORFI3','GOUAN1','GOUAN2','GOUAN3','GOUKA1','GOUKA2','GOUKA3','GUILM1','GUILM2','GUILM3','IDADJ1','IDADJ2','IDADJ3','IKEMO1','IKEMO2','IKEMO3','KABOU1','KABOU2','KABOU3','KAOBA1','KAOBA2','KAOBA3','KEDEK1','KEDEK2','KEDEK3','KIKA1','KIKA2','KIKA3','KILIB1','KILIB2','KILIB3','KOGNI1','KOGNI2','KOGNI3','KOKOB1','KOKOB2','KOKOB3','KOKOR1','KOKOR2','KOKOR3','KOLOK1','KOLOK2','KOLOK3','KOMDE1','KOMDE2','KOMDE3','KOTOP1','KOTOP2','KOTOP3','KOUAN1','KOUAN2','KOUAN3','KOUAT1','KOUAT2','KOUAT3','KOUNT1','KOUNT2','KOUNT3','KOUTC1','KOUTC2','KOUTC3','KPAND1','KPAND2','KPAND3','KPATA1','KPATA2','KPATA3','KPESS1','KPESS2','KPESS3','LAHOT1','LAHOT2','LAHOT3','LOUGB1','LOUGB2','LOUGB3','MADJA1','MADJA2','MADJA3','MANIG1','MANIG2','MANIG3','MANI21','MANI22','MANI23','MANTA1','MANTA2','MANTA3','MATER1','MATER2','MATER3','NAGAY1','NAGAY2','NAGAY3','NASSO1','NASSO2','NASSO3','DNATI11','DNATI12','DNATI13','NATI11','NATI12','NATI13','NAT101','NAT102','NAT103','NAT111','NAT112','NAT113','NAT121','NAT122','NAT123','NAT131','NAT132','NAT133','NATI21','NATI22','NATI23','NATI31','NATI32','NATI33','NATI41','NATI42','NATI43','NATI51','NATI52','NATI53','NATI61','NATI62','NATI63','NATI71','NATI72','NATI73','NATI81','NATI82','NATI83','NATI91','NATI92','NATI93','NDAHON1','NDAHON2','NDAHON3','NIEKE1','NIEKE2','NIEKE3','NODI1','NODI2','NODI3','OKEOW1','OKEOW2','OKEOW3','OKOSE1','OKOSE2','OKOSE3','OLOGB1','OLOGB2','OLOGB3','ONKLO1','ONKLO2','ONKLO3','OROUK1','OROUK2','OROUK3','OUAKE1','OUAKE2','OUAKE3','OUEDE1','OUEDE2','OUEDE3','OUEOE1','OUEOE2','OUEOE3','OUESS1','OUESS2','OUESS3','OUES21','OUES22','OUES23','OUES31','OUES32','OUES33','OUOGH1','OUOGH2','OUOGH3','OWOLA1','OWOLA2','OWOLA3','PABEG1','PABEG2','PABEG3','PAPAR1','PAPAR2','PAPAR3','DPATAR1','PATAR1','PATAR2','PATAR3','PELEB1','PELEB2','PELEB3','PENES1','PENES2','PENES3','PERMA1','PERMA2','PERMA3','PIRA1','PIRA2','PIRA3','PORGA1','PORGA2','PORGA3','PREKE1','PREKE2','PREKE3','ANAFO1','BOKOR1','BOROK1','BOUND1','BOUNG1','BOUTO1','DABOG1','DONDJ1','GALAT1','GBAHA1','GNANG1','GORGO1','GOUNT1','KABAR1','KATAN1','KIKEL1','KOUHO1','KOUBA1','KOUBO1','KOUTO1','LOAKA1','MAHON1','MAKA1','MALET1','MAMOU1','MOUNO1','NATTA1','NIARS1','NINGO1','OROUB1','OUAKI1','PENTI1','PINGO1','SIENO1','SINAO1','SOULA1','SOWEI1','TAMPO1','TASSI1','TCHAL1','TECTI1','TEDON1','YEBES1','YEDEK1','YOPIA1','SALAG1','SALAG2','SALAG3','SAVE11','SAVE12','SAVE13','SAVE21','SAVE22','SAVE23','SAVE31','SAVE32','SAVE33','SAVE41','SAVE42','SAVE43','SAVE51','SAVE52','SAVE53','SEKEG1','SEKEG2','SEKEG3','SEMER1','SEMER2','SEMER3','SINGR1','SINGR2','SINGR3','SOMGA1','SOMGA2','SOMGA3','SONTA1','SONTA2','SONTA3','SOWIA1','SOWIA2','SOWIA3','SUCOB1','SUCOB2','SUCOB3','DTANGU1','DTANGU4','TANGU1','TANGU2','TANGU3','DTANG21','DTANG22','TANG21','TANG22','TANG23','TANG31','TANG32','TANG33','TANTE1','TANTE2','TANTE3','TAPOG1','TAPOG2','TAPOG3','TCHAH1','TCHAG1','TCHAG2','TCHAG3','TCHETO1','TCHETO2','TCHETO3','THIO1','THIO2','THIO3','TOKO1','TOKO2','TOKO3','TOUCO1','TOUCO2','TOUCO3','DTOUI1','DTOUI2','DTOUI3','TOUI1','TOUI2','TOUI3','VANH1','VANH2','VANH3','WAMA1','WAMA2','WAMA3','YAKAB1','YAKAB2','YAKAB3','YAOUI1','YAOUI2','YAOUI3','YARIK1','YARIK2','YARIK3','YEHON1','YEHON2','YEHON3','YOUAK1','YOUAK2','YOUAK3']
                    },
                },
            },

            # -----------------------------------------------------------------
            # Huawei 2G
            # -----------------------------------------------------------------
            "huawei": {
                "label"    : "Huawei",
                "sql_file" : "huawei_2g.sql",
                "date_col" : "h.date",
                "time_col" : "h.time",
                "cell_col" : "h.CELL_NAME",

                "kpi_groups": {
                    "CSSR (%)": {
                        "columns": ["CSSR_HUAWEI"],
                        "threshold": 99
                    },
                    "CDR (%)": {
                        "columns": ["CDR_HUAWEI"],
                        "threshold": 1
                    },
                    "CBR (%)": {
                        "columns": ["CBR_HUAWEI"],
                        "threshold": 1
                    },
                    "TCH Congestion Rate (%)": {
                        "columns": ["TCH_CONGESTION_RATE_HUAWEI"],
                        "threshold": None
                    },
                    "SDCCH Congestion Rate (%)": {
                        "columns": ["SDCCH_CONGESTION_RATE_HUAWEI"],
                        "threshold": None
                    },
                    "SDCCH Drop Rate (%)": {
                        "columns": ["SDCCH_DROP_RATE_HUAWEI"],
                        "threshold": None
                    },
                    "TCH Assignment Success Rate (%)": {
                        "columns": ["TCH_ASSIGNMENT_SUCCESS_RATE_HUAWEI"],
                        "threshold": None
                    },
                    "SDCCH Traffic (Erlang)": {
                        "columns": ["SDCCH_TRAFFIC_HUAWEI"],
                        "threshold": None
                    },
                    "Cell Availability Rate (%)": {
                        "columns": ["CELL_AVAILABILITY_RATE_HUAWEI"],
                        "threshold": 99
                    },
                    "Traffic Voice (Erlang)": {
                        "columns": ["TRAFFIC_VOIX_HUAWEI"],
                        "threshold": None
                    },
                    "Handover Success Rate (%)": {
                        "columns": ["HANDOVER_SUCCESS_RATE_HUAWEI"],
                        "threshold": None
                    },
                },

                "batches": {
                    "cluster_1": {
                        "label": "110 Cell impovment 10 Mars",
                        "cells": _HUAWEI_2G_CLUSTER_1,
                    },
                    "cluster_2": {
                        "label": "160 cell action worst cell 10 mars",
                        "cells": _HUAWEI_2G_CLUSTER_2,
                    },
                     "cluster_3": {
                        "label": "29 CELL ABDEL_AZIZ",
                        "cells": _HUAWEI_2G_CELL_29_MARCH,
                    },
                     "cluster_4": {
                        "label": "2G NEW BATCH TAC LAC",
                        "cells": _HUAWEI_2G_TAC_LAC_SECOND_BATCH,
                    },
                },
            },
        },
    },

    # =========================================================================
    # 3G
    # =========================================================================
    "3g": {
        "label": "3G",
        "vendors": {

            # -----------------------------------------------------------------
            # Ericsson 3G
            # -----------------------------------------------------------------
            "ericsson": {
                "label"    : "Ericsson",
                "sql_file" : "ericsson_3g.sql",
                "date_col" : "DATE",
                "time_col" : "TIME",
                "cell_col" : "CELL_NAME",

                "kpi_groups": {
                    "3G CS CSSR (%)": {
                        "columns": ["CS_CSSR"],
                        "threshold": None
                    },
                    "3G CS Drop Rate (%)": {
                        "columns": ["CS_DROP"],
                        "threshold": None
                    },
                    "3G CS CBR (%)": {
                        "columns": ["CS_CBR"],
                        "threshold": None
                    },
                    "3G PS CSSR (%)": {
                        "columns": ["PS_CSSR"],
                        "threshold": None
                    },
                    "3G PS Drop Rate (%)": {
                        "columns": ["PS_DROP"],
                        "threshold": None
                    },
                    "3G DL Throughput (kbps)": {
                        "columns": ["DEBIT_DL"],
                        "threshold": None
                    },
                    "3G UL Throughput (kbps)": {
                        "columns": ["DEBIT_UL"],
                        "threshold": None
                    },
                    "3G UL Cell Throughput ARCEP (kbps)": {
                        "columns": ["DEBIT_UL_CELL_ARCEP"],
                        "threshold": None
                    },
                    "3G Cell Availability (%)": {
                        "columns": ["CELL_AVAILABILITY"],
                        "threshold": None
                    },
                    "3G RL Add Success Rate (%)": {
                        "columns": ["RL_ADD_SUCCESS_RATE"],
                        "threshold": None
                    },
                    "3G IRAT HO Success Rate (%)": {
                        "columns": ["IRAT_HO_SUCCESS_RATE"],
                        "threshold": None
                    },
                    "3G Traffic Voice": {
                        "columns": ["TRAFFIC_VOIX"],
                        "threshold": None
                    },
                    "3G Traffic Data (GB)": {
                        "columns": ["TRAFFIC_DATA_GB"],
                        "threshold": None
                    },
                },

                # Add batches here when ready:
                # "zone_north": {"label": "North Zone", "cells": _ERICSSON_3G_ZONE_NORTH},
             


                "batches": {
                     "cluster_1": {
                        "label": "LAC TAC CHANGE",
                        "cells": _ERICSSON_3G_CLUSTER_1,
                    },
                     "cluster_2": {
                        "label": "LAC TAC CHANGE V2",
                        "cells": ['UDONTA7','UDONTA8','UDONTA9'],
                    },
                     "cluster_3": {
                        "label": "VEPC_V2_FIRST_BATCH_PKRNC02",
                        "cells": ['UAFFES7','UAFFES8','UAFFES9','UAGBAD7','UAGBAD8','UAGBAD9','UAGOUA7','UAGOUA8','UAGOUA9','UAKLAN7','UAKLAN8','UAKLAN9','UALAFI7','UALAFI8','UALAFI9','UALEDJ7','UALEDJ8','UALEDJ9','UANAND7','UANAND8','UANAND9','UANOUM7','UANOUM8','UANOUM9','UAORO7','UAORO8','UAORO9','UASSAN7','UASSAN8','UASSAN9','UAZRAO7','UAZRAO8','UAZRAO9','UBADJO7','UBADJO8','UBADJO9','UBAKOU7','UBAKOU8','UBAKOU9','UBANTE7','UBANTE8','UBANTE9','UBANT27','UBANT28','UBANT29','UBAREI7','UBAREI8','UBAREI9','UBARIE7','UBARIE8','UBARIE9','UBASSI7','UBASSI8','UBASSI9','UBASS27','UBASS28','UBASS29','UBAYAK7','UBAYAK8','UBAYAK9','UBELL7','UBELL8','UBELL9','UBEREC7','UBEREC8','UBEREC9','UBERE27','UBERE28','UBERE29','UBIGUI7','UBIGUI8','UBIGUI9','UBILKO7','UBILKO8','UBILKO9','UBIRNI7','UBIRNI8','UBIRNI9','UBOBE7','UBOBE8','UBOBE9','UBODI7','UBODI8','UBODI9','UBONGO7','UBONGO8','UBONGO9','UBOUGO7','UBOUGO8','UBOUGO9','UBOUKO7','UBOUKO8','UBOUKO9','UCHABI7','UCHABI8','UCHABI9','UCOBLI7','UCOBLI8','UCOBLI9','UCOPAR7','UCOPAR8','UCOPAR9','UCOTIA7','UCOTIA8','UCOTIA9','UDARIN7','UDARIN8','UDARIN9','UDASAR7','UDASAR8','UDASAR9','UDATOR7','UDATOR8','UDATOR9','UDJEGB7','UDJEGB8','UDJEGB9','UDJOU17','UDJOU18','UDJOU19','UDJO107','UDJO108','UDJO109','UDJOU27','UDJOU28','UDJOU29','UDJOU31','UDJOU32','UDJOU33','UDJOU34','UDJOU35','UDJOU36','UDJOU3A','UDJOU3B','UDJOU3C','UDJOU47','UDJOU48','UDJOU49','UDJOU57','UDJOU58','UDJOU59','UDJOU67','UDJOU68','UDJOU69','UDJOU77','UDJOU78','UDJOU79','UDJOU87','UDJOU88','UDJOU89','UDJOU97','UDJOU98','UDJOU99','UDOGUE7','UDOGUE8','UDOGUE9','UFAKA7','UFAKA8','UFAKA9','UFIROU7','UFIROU8','UFIROU9','UFOTEN7','UFOTEN8','UFOTEN9','UFOMON7','UFOMON8','UFOMON9','UGAOUN7','UGAOUN8','UGAOUN9','UGBANL7','UGBANL8','UGBANL9','UGLAZ17','UGLAZ18','UGLAZ19','UGLAZ27','UGLAZ28','UGLAZ29','UGLAZ37','UGLAZ38','UGLAZ39','UGLAZ47','UGLAZ48','UGLAZ49','UGOBE7','UGOBE8','UGOBE9','UGOGOR7','UGOGOR8','UGOGOR9','UGORFI7','UGORFI8','UGORFI9','UGOUAN7','UGOUAN8','UGOUAN9','UGOUKA7','UGOUKA8','UGOUKA9','UGUILM7','UGUILM8','UGUILM9','UIDADJ7','UIDADJ8','UIDADJ9','UIKEMO7','UIKEMO8','UIKEMO9','UKABOU7','UKABOU8','UKABOU9','UKAOBA7','UKAOBA8','UKAOBA9','UKEDEK7','UKEDEK8','UKEDEK9','UKIKA7','UKIKA8','UKIKA9','UKILIB7','UKILIB8','UKILIB9','UKOGNI7','UKOGNI8','UKOGNI9','UKOKOB7','UKOKOB8','UKOKOB9','UKOKOR7','UKOKOR8','UKOKOR9','UKOLOK7','UKOLOK8','UKOLOK9','UKOMDE7','UKOMDE8','UKOMDE9','UKOTOP7','UKOTOP8','UKOTOP9','UKOUAN7','UKOUAN8','UKOUAN9','UKOUAT7','UKOUAT8','UKOUAT9','UKOUNT7','UKOUNT8','UKOUNT9','UKOUTC7','UKOUTC8','UKOUTC9','UKPAND7','UKPAND8','UKPAND9','UPATAB7','UPATAB8','UPATAB9','UKPESS7','UKPESS8','UKPESS9','ULAHOT7','ULAHOT8','ULAHOT9','ULOUGB7','ULOUGB8','ULOUGB9','UMADJA7','UMADJA8','UMADJA9','UDMANI7','UDMANI8','UDMANI9','UMANI27','UMANI28','UMANI29','UMANTA7','UMANTA8','UMANTA9','UMATER7','UMATER8','UMATER9','UNAGAY7','UNAGAY8','UNAGAY9','UNASSO7','UNASSO8','UNASSO9','UNATI17','UNATI18','UNATI19','UNAT107','UNAT108','UNAT109','UNAT117','UNAT118','UNAT119','UNAT127','UNAT128','UNAT129','UNAT137','UNAT138','UNAT139','UNATI27','UNATI28','UNATI29','UNATI37','UNATI38','UNATI39','UNATI47','UNATI48','UNATI49','UNATI57','UNATI58','UNATI59','UNATI67','UNATI68','UNATI69','UNATI77','UNATI78','UNATI79','UNATI87','UNATI88','UNATI89','UNATI97','UNATI98','UNATI99','UNDAHO7','UNDAHO8','UNDAHO9','UNIEKE7','UNIEKE8','UNIEKE9','UNODI7','UNODI8','UNODI9','UOKEOW7','UOKEOW8','UOKEOW9','UOKOSE7','UOKOSE8','UOKOSE9','UOLOGB7','UOLOGB8','UOLOGB9','UONKLO7','UONKLO8','UONKLO9','UOROUK7','UOROUK8','UOROUK9','UOUAKE7','UOUAKE8','UOUAKE9','UOUEDE7','UOUEDE8','UOUEDE9','UOUEOU7','UOUEOU8','UOUEOU9','UOUESS7','UOUESS8','UOUESS9','UOUES27','UOUES28','UOUES29','UOUES37','UOUES38','UOUES39','UOUOGH7','UOUOGH8','UOUOGH9','UOWOLA7','UOWOLA8','UOWOLA9','UPABEG7','UPABEG8','UPABEG9','UPAPAR7','UPAPAR8','UPAPAR9','UPATAR7','UPATAR8','UPATAR9','UPELEB7','UPELEB8','UPELEB9','UPENES7','UPENES8','UPENES9','UPERMA7','UPERMA8','UPERMA9','UPIRA7','UPIRA8','UPIRA9','UPORGA7','UPORGA8','UPORGA9','UPREKE7','UPREKE8','UPREKE9','UANAFO7','UBOKOR7','UBOROK7','UBOUND7','UBOUTO7','UDABOG7','UDONDJ7','UGALAT7','UGBAHA7','UGNANG7','UGORGO7','UGOUNT7','UKABAR7','UKATAN7','UKIKEL7','UKOUHO7','UKOUBA7','UKOUBO7','UKOUTO7','ULOAKA7','UMAHON7','UMAKA7','UMALET7','UMAMOU7','UMOUNO7','UNATTA7','UNIARS7','UNINGO7','UOROUB7','UOUAKI7','UPENTI7','UPINGO7','USIENO7','USINAO7','USOULA7','USOWEI7','UTAMPO7','UTASSI7','UTCHAL7','UTCHAH7','UTECTI7','UTEDON7','UYEBES7','UYEDEK7','UYOPIA7','USALAG7','USALAG8','USALAG9','USAVE17','USAVE18','USAVE19','USAVE27','USAVE28','USAVE29','USAVE37','USAVE38','USAVE39','USAVE47','USAVE48','USAVE49','USAVE57','USAVE58','USAVE59','USEKEG7','USEKEG8','USEKEG9','USEMER7','USEMER8','USEMER9','USINGR7','USINGR8','USINGR9','USOMGA7','USOMGA8','USOMGA9','USONTA7','USONTA8','USONTA9','USOWIA7','USOWIA8','USOWIA9','USUCOB7','USUCOB8','USUCOB9','UTANGU7','UTANGU8','UTANGU9','UTANG7','UTANG8','UTANG9','UTANG37','UTANG38','UTANG39','UTANTE7','UTANTE8','UTANTE9','UTAPOG7','UTAPOG8','UTAPOG9','UTCHAG7','UTCHAG8','UTCHAG9','UTCHE7','UTCHE8','UTCHE9','UTHIO7','UTHIO8','UTHIO9','UTOKO7','UTOKO8','UTOKO9','UTOUCO7','UTOUCO8','UTOUCO9','UTOUI7','UTOUI8','UTOUI9','UVANHO7','UVANHO8','UVANHO9','UWAMA7','UWAMA8','UWAMA9','UYAKAB7','UYAKAB8','UYAKAB9','UYAOUI7','UYAOUI8','UYAOUI9','UYARIK7','UYARIK8','UYARIK9','UYEHON7','UYEHON8','UYEHON9','UYOUAK7','UYOUAK8','UYOUAK9'],
                    },
                    
                },


            },
        },
    },

    # =========================================================================
    # 4G
    # =========================================================================
    "4g": {
        "label": "4G",
        "vendors": {

            # -----------------------------------------------------------------
            # Ericsson 4G
            # -----------------------------------------------------------------
            "ericsson": {
                "label"    : "Ericsson",
                "sql_file" : "ericsson_4g.sql",
                "date_col" : "DATE",
                "time_col" : "TIME",
                "cell_col" : "CELL_NAME",

                "kpi_groups": {
                    "4G PS CSSR (%)": {
                        "columns": ["PS_CSSR"],
                        "threshold": None
                    },
                    "4G ERAB Drop Rate (%)": {
                        "columns": ["ERAB_DROP"],
                        "threshold": None
                    },
                    "4G DL Cell Throughput (kbps)": {
                        "columns": ["DEBIT_DL"],
                        "threshold": None
                    },
                    "4G UL Cell Throughput (kbps)": {
                        "columns": ["DEBIT_UL"],
                        "threshold": None
                    },
                    "4G DL User Throughput (kbps)": {
                        "columns": ["DL_USER_THP"],
                        "threshold": None
                    },
                    "4G UL User Throughput (kbps)": {
                        "columns": ["UL_USER_THP"],
                        "threshold": None
                    },
                    "4G Intra HO Success Rate (%)": {
                        "columns": ["INTRA_HOSR"],
                        "threshold": None
                    },
                    "4G Inter HO Success Rate (%)": {
                        "columns": ["INTER_HOSR"],
                        "threshold": None
                    },
                    "4G PRB Utilization (%)": {
                        "columns": ["PRB_UTILIZATION"],
                        "threshold": None
                    },
                    "4G PRB Utilization DL New (%)": {
                        "columns": ["PRB_UTILIZATION_DL_NEW"],
                        "threshold": None
                    },
                    "4G Cell Availability with Manual (%)": {
                        "columns": ["CELL_AVAILABILITY_WITH_MANUAL"],
                        "threshold": None
                    },
                    "4G Cell Availability (%)": {
                        "columns": ["CELL_AVAILABILITY"],
                        "threshold": None
                    },
                    "4G CSFB Success Rate (%)": {
                        "columns": ["CSFB_SR"],
                        "threshold": None
                    },
                    "4G ERAB Failures (count)": {
                        "columns": ["LTE_ERAB_FAILURE"],
                        "threshold": None
                    },
                    "4G Active Users": {
                        "columns": ["active_user"],
                        "threshold": None
                    },
                    "4G Traffic Data (GB)": {
                        "columns": ["TRAFFIC_DATA_GB"],
                        "threshold": None
                    },
                },

                # Add batches here when ready:
                # "zone_north": {"label": "North Zone", "cells": _ERICSSON_4G_ZONE_NORTH},
            
             
                    "batches": {
                        "cluster_1": {
                            "label": "LAC TAC CHANGE",
                            "cells": _ERICSSON_4G_CLUSTER_1,
                        },
                        "cluster_2": {
                            "label": "LAC TAC CHANGE V2",
                            "cells":  ['LFONKP1','LFONKP2','LFONKP3','LKOHOU1','LKOHOU2','LKOHOU3','LKPAKP1','LKPAKP2','LKPAKP3','LKPAKP7','LKPAKP8','LKPAKP9','LKPAKPA','LKPAKPB','LKPAKPC','LMANSO1','LMANSO2','LMANSO3','LYAGBA1','LYAGBA2','LYAGBA3','LZATANT1','LZATANT2','LZATANT3','LZATANT7','LZATANT8','LZATANT9','LZATANTA','LZATANTB','LZATANTC']
                        },
                         "cluster_2": {
                            "label": "VEPC_V2_BATCH_1_PKBSC06_2G",
                            "cells":  ['LAFFES1','LAFFES2','LAFFES3','LAGBAD1','LAGBAD2','LAGBAD3','LAGOUA1','LAGOUA2','LAGOUA3','LAKLAN1','LAKLAN2','LAKLAN3','LALAFI1','LALAFI2','LALAFI3','LALEDJ1','LALEDJ2','LALEDJ3','LANAN1','LANAN2','LANAN3','LANOUM1','LANOUM2','LANOUM3','LAORO1','LAORO2','LAORO3','LAZRAO1','LAZRAO2','LAZRAO3','LBADJO1','LBADJO2','LBADJO3','LBAKOU1','LBAKOU2','LBAKOU3','LBAREI1','LBAREI2','LBAREI3','LBARIE1','LBARIE2','LBARIE3','LBASSI21','LBASSI22','LBASSI23','LBASSI27','LBASSI28','LBASSI29','LBASSI2A','LBASSI2B','LBASSI2C','LBAYAK1','LBAYAK2','LBAYAK3','LBERE21','LBERE22','LBERE23','LBIGUI1','LBIGUI2','LBIGUI3','LBILKO1','LBILKO2','LBILKO3','LBIRNI1','LBIRNI2','LBIRNI3','LBOBE1','LBOBE2','LBOBE3','LBONGO1','LBONGO2','LBONGO3','LBOUGO1','LBOUGO2','LBOUGO3','LCOPAR1','LCOPAR2','LCOPAR3','LCOTIA1','LCOTIA2','LCOTIA3','LDARIN1','LDARIN2','LDARIN3','LDASAR1','LDASAR2','LDASAR3','LDATORI1','LDATORI2','LDATORI3','LDJEGB1','LDJEGB2','LDJEGB3','LDJO101','LDJO102','LDJO103','LDJO104','LDJO105','LDJO106','LDJO107','LDJO108','LDJO109','LDJO10A','LDJO10B','LDJO10C','LDJOU81','LDJOU82','LDJOU83','LDJOU91','LDJOU92','LDJOU93','LDJOU94','LDJOU95','LDJOU96','LDJOU97','LDJOU98','LDJOU99','LDJOU9A','LDJOU9B','LDJOU9C','LDOGUE1','LDOGUE2','LDOGUE3','LFOMON1','LFOMON2','LFOMON3','LGAOUN1','LGAOUN2','LGAOUN3','LDJOU41','LDJOU42','LDJOU43','LDJOU44','LDJOU45','LDJOU46','LDJOU51','LDJOU52','LDJOU53','LDJOU54','LDJOU55','LDJOU56','LDJOU61','LDJOU62','LDJOU63','LDJOU64','LDJOU65','LDJOU66','LGLAZ11','LGLAZ12','LGLAZ13','LGLAZ17','LGLAZ18','LGLAZ19','LGLAZ1A','LGLAZ1B','LGLAZ1C','LNATI81','LNATI82','LNATI83','LNATI84','LNATI85','LNATI86','LGLAZ41','LGLAZ42','LGLAZ43','LGLAZ47','LGLAZ48','LGLAZ49','LGLAZ4A','LGLAZ4B','LGLAZ4C','LGOGOR1','LGOGOR2','LGOGOR3','LGORFI1','LGORFI2','LGORFI3','LGOUAN1','LGOUAN2','LGOUAN3','LIDADJ1','LIDADJ2','LIDADJ3','LIKEMO1','LIKEMO2','LIKEMO3','LKABOU1','LKABOU2','LKABOU3','LKAOBA1','LKAOBA2','LKAOBA3','LKOGNI1','LKOGNI2','LKOGNI3','LKOKOB1','LKOKOB2','LKOKOB3','LKOMDE1','LKOMDE2','LKOMDE3','LKOTOP1','LKOTOP2','LKOTOP3','LKOUAT1','LKOUAT2','LKOUAT3','LKOUAT7','LKOUAT8','LKOUAT9','LKOUATA','LKOUATB','LKOUATC','LKOUNT1','LKOUNT2','LKOUNT3','LKOUTC1','LKOUTC2','LKOUTC3','LKPAND1','LKPAND2','LKPAND3','LKPATA1','LKPATA2','LKPATA3','LASSAN1','LASSAN2','LASSAN3','LASSAN7','LASSAN8','LASSAN9','LASSANA','LASSANB','LASSANC','LBANTE1','LBANTE2','LBANTE3','LBANTE7','LBANTE8','LBANTE9','LBANTEA','LBANTEB','LBANTEC','LBANT21','LBANT22','LBANT23','LBASSI1','LBASSI2','LBASSI3','LBELL1','LBELL2','LBELL3','LBEREC1','LBEREC2','LBEREC3','LBODI1','LBODI2','LBODI3','LBOUKO1','LBOUKO2','LBOUKO3','LCHABI1','LCHABI2','LCHABI3','LCHABI7','LCHABI8','LCHABI9','LCHABIA','LCHABIB','LCHABIC','LCOBLI1','LCOBLI2','LCOBLI3','LCOBLI7','LCOBLI8','LCOBLI9','LDJOU11','LDJOU12','LDJOU13','LDJOU14','LDJOU15','LDJOU16','LDJOU21','LDJOU22','LDJOU23','LDJOU24','LDJOU25','LDJOU26','LDJOU31','LDJOU32','LDJOU33','LDJOU34','LDJOU35','LDJOU36','LDJOU71','LDJOU72','LDJOU73','LDJOU74','LDJOU75','LDJOU76','LFAKA1','LFAKA2','LFAKA3','LFIROU1','LFIROU2','LFIROU3','LFOTEN1','LFOTEN2','LFOTEN3','LGBANL1','LGBANL2','LGBANL3','LGLAZ21','LGLAZ22','LGLAZ23','LGLAZ27','LGLAZ28','LGLAZ29','LGLAZ2A','LGLAZ2B','LGLAZ2C','LGLAZ31','LGLAZ32','LGLAZ33','LGLAZ37','LGLAZ38','LGLAZ39','LGLAZ3A','LGLAZ3B','LGLAZ3C','LGOBE1','LGOBE2','LGOBE3','LGOUKA1','LGOUKA2','LGOUKA3','LGUILM1','LGUILM2','LGUILM3','LKEDEK1','LKEDEK2','LKEDEK3','LKIKA1','LKIKA2','LKIKA3','LKILIB1','LKILIB2','LKILIB3','LKILIB7','LKILIB8','LKILIB9','LKILIBA','LKILIBB','LKILIBC','LKOKOR1','LKOKOR2','LKOKOR3','LKOLOK1','LKOLOK2','LKOLOK3','LKOUAN1','LKOUAN2','LKOUAN3','LKOUAN7','LKOUAN8','LKOUAN9','LKOUANA','LKOUANB','LKOUANC','LKPESS1','LKPESS2','LKPESS3','LDMANI1','LDMANI2','LDMANI3','LMANTA1','LMANTA2','LMANTA3','LMATER1','LMATER2','LMATER3','LMATER7','LMATER8','LMATER9','LMATERA','LMATERB','LMATERC','LNATI11','LNATI12','LNATI13','LNATI14','LNATI15','LNATI16','LNATI21','LNATI22','LNATI23','LNATI24','LNATI25','LNATI26','LNATI31','LNATI32','LNATI33','LNATI34','LNATI35','LNATI36','LNATI41','LNATI42','LNATI43','LNATI44','LNATI45','LNATI46','LNATI51','LNATI52','LNATI53','LNATI54','LNATI55','LNATI56','LNATI61','LNATI62','LNATI63','LNATI64','LNATI65','LNATI66','LNATI71','LNATI72','LNATI73','LNATI74','LNATI75','LNATI76','LNDAHO1','LNDAHO2','LNDAHO3','LOUAKE1','LOUAKE2','LOUAKE3','LOUAKE7','LOUAKE8','LOUAKE9','LOUAKEA','LOUAKEB','LOUAKEC','LOUEDE1','LOUEDE2','LOUEDE3','LOUESS1','LOUESS2','LOUESS3','LOUESS7','LOUESS8','LOUESS9','LOUESSA','LOUESSB','LOUESSC','LOUES21','LOUES22','LOUES23','LOUES27','LOUES28','LOUES29','LOUES2A','LOUES2B','LOUES2C','LOUOGH1','LOUOGH2','LOUOGH3','LPAPAR1','LPAPAR2','LPAPAR3','LPATAR1','LPATAR2','LPATAR3','LPERMA1','LPERMA2','LPERMA3','LPORGA1','LPORGA2','LPORGA3','LSAVE11','LSAVE12','LSAVE13','LSAVE17','LSAVE18','LSAVE19','LSAVE1A','LSAVE1B','LSAVE1C','LSAVE21','LSAVE22','LSAVE23','LSAVE24','LSAVE25','LSAVE26','LSAVE27','LSAVE28','LSAVE29','LSAVE2A','LSAVE2B','LSAVE2C','LSAVE31','LSAVE32','LSAVE33','LSAVE34','LSAVE35','LSAVE36','LSAVE37','LSAVE38','LSAVE39','LSAVE3A','LSAVE3B','LSAVE3C','LSAVE41','LSAVE42','LSAVE43','LSAVE47','LSAVE48','LSAVE49','LSAVE4A','LSAVE4B','LSAVE4C','LSUCOB1','LSUCOB2','LSUCOB3','LTANGU1','LTANGU2','LTANGU3','LTANGU4','LTANGU5','LTANGU6','LTANGU7','LTANGU8','LTANGU9','LTANGUA','LTANGUB','LTANGUC','LTANG1','LTANG2','LTANG3','LTANG4','LTANG5','LTANG6','LTANG7','LTANG8','LTANG9','LTANGA','LTANGB','LTANGC','LTANTE1','LTANTE2','LTANTE3','LTANTE7','LTANTE8','LTANTE9','LTANTEA','LTANTEB','LTANTEC','LTAPOG1','LTAPOG2','LTAPOG3','LTCHAG1','LTCHAG2','LTCHAG3','LTOUI1','LTOUI2','LTOUI3','LVANHO1','LVANHO2','LVANHO3','LYAOUI1','LYAOUI2','LYAOUI3','LLAHOT1','LLAHOT2','LLAHOT3','LLOUGB1','LLOUGB2','LLOUGB3','LMADJA1','LMADJA2','LMADJA3','LMANI21','LMANI22','LMANI23','LNAGAY1','LNAGAY2','LNAGAY3','LNASSO1','LNASSO2','LNASSO3','LNAT101','LNAT102','LNAT103','LNAT104','LNAT105','LNAT106','LNAT107','LNAT108','LNAT109','LNAT10A','LNAT10B','LNAT10C','LNAT111','LNAT112','LNAT113','LNAT117','LNAT118','LNAT119','LNAT11A','LNAT11B','LNAT11C','LNAT121','LNAT122','LNAT123','LNAT127','LNAT128','LNAT129','LNAT12A','LNAT12B','LNAT12C','LNAT131','LNAT132','LNAT133','LNAT137','LNAT138','LNAT139','LNAT13A','LNAT13B','LNAT13C','LNATI91','LNATI92','LNATI93','LNATI94','LNATI95','LNATI96','LNATI97','LNATI98','LNATI99','LNATI9A','LNATI9B','LNATI9C','LNIEKE1','LNIEKE2','LNIEKE3','LNODI1','LNODI2','LNODI3','LOKEOW1','LOKEOW2','LOKEOW3','LOKOSE1','LOKOSE2','LOKOSE3','LOLOGB1','LOLOGB2','LOLOGB3','LONKLO1','LONKLO2','LONKLO3','LOROUK1','LOROUK2','LOROUK3','LOUEOE1','LOUEOE2','LOUEOE3','LOUES31','LOUES32','LOUES33','LOUES37','LOUES38','LOUES39','LOUES3A','LOUES3B','LOUES3C','LOWOLA1','LOWOLA2','LOWOLA3','LPABEG1','LPABEG2','LPABEG3','LPELEB1','LPELEB2','LPELEB3','LPENES1','LPENES2','LPENES3','LPIRA1','LPIRA2','LPIRA3','LPREKE1','LPREKE2','LPREKE3','LANAFO1','LBOKOR1','LBOROK1','LBOUND1','LBOUTO1','LDABOG1','LDONDJ1','LGALAT1','LGBAHA1','LGNANG1','LGORGO1','LGOUNT1','LKABAR1','LKATAN1','LKIKEL1','LKOUHO1','LKOUBO1','LKOUTO1','LLOAKA1','LMAHON1','LMAKA1','LMALET1','LMAMOU1','LMOUNO1','LNATTA1','LNIARS1','LNINGO1','LOROUB1','LOUAKI1','LPENTI1','LPINGO1','LSIENO1','LSINAO1','LSOULA1','LSOWEI1','LTAMPO1','LTASSI1','LTCHAL1','LTCHAH1','LTECTI1','LTEDON1','LYEBES1','LYEDEK1','LYOPIA1','LSALAG1','LSALAG2','LSALAG3','LSAVE51','LSAVE52','LSAVE53','LSEKEG1','LSEKEG2','LSEKEG3','LSEMER1','LSEMER2','LSEMER3','LSINGR1','LSINGR2','LSINGR3','LSOMGA1','LSOMGA2','LSOMGA3','LSONTA1','LSONTA2','LSONTA3','LSOWIA1','LSOWIA2','LSOWIA3','LTANG31','LTANG32','LTANG33','LTANG37','LTANG38','LTANG39','LTANG3A','LTANG3B','LTANG3C','LTCHETO1','LTCHETO2','LTCHETO3','LTHIO1','LTHIO2','LTHIO3','LTOKO1','LTOKO2','LTOKO3','LTOUCO1','LTOUCO2','LTOUCO3','LWAMA1','LWAMA2','LWAMA3','LYAKAB1','LYAKAB2','LYAKAB3','LYARIK1','LYARIK2','LYARIK3','LYEHON1','LYEHON2','LYEHON3','LYOUAK1','LYOUAK2','LYOUAK3']
                        },
                },

            },
        },
    },
}
