

SELECT
{outer_select_geo}    sum_cssr_failure                                                                                        AS CSR_FAILURES,
    ROUND(100 * sum_cssr_failure        / NULLIF(SUM(sum_cssr_failure)        OVER (), 0), 4)               AS Weight_CSR_FAILURES,

    SUM_SDCCH_ASSIGN_FAILS                                                                                  AS SDCCH_ASSIGN_FAILS,
   -- ROUND(100 * SDCCH_ASSIGN_FAILS / CSR_FAILURES, 2) AS 'WEIGHT_SDCCH_ASSIGN_IN_CELL(%)',
    ROUND(100 * SUM_SDCCH_ASSIGN_FAILS  / NULLIF(SUM(SUM_SDCCH_ASSIGN_FAILS)  OVER (), 0), 4)               AS 'GLOBAL_WEIGHT_SDCCH_ASSIGN(%)',

    SUM_SDCCH_DROPS                                                                                         AS SDCCH_DROPS,
   -- ROUND(100 * SDCCH_DROPS / CSR_FAILURES, 2) AS 'WEIGHT_SDCCH_DROPS_IN_CELL(%)',
    ROUND(100 * SUM_SDCCH_DROPS         / NULLIF(SUM(SUM_SDCCH_DROPS)         OVER (), 0), 4)               AS 'GLOBAL_WEIGHT_SDCCH_DROPS(%)',

    SUM_TCH_ASSIGN_FAILS                                                                                    AS TCH_ASSIGN_FAILS,
   -- ROUND(100 * TCH_ASSIGN_FAILS / CSR_FAILURES, 2) AS 'WEIGHT_TCH_ASSIGN_IN_CELL(%)',
    ROUND(100 * SUM_TCH_ASSIGN_FAILS    / NULLIF(SUM(SUM_TCH_ASSIGN_FAILS)    OVER (), 0), 4)               AS 'GLOBAL_WEIGHT_TCH_ASSIGN(%)',

    SUM_TCH_DROPS                                                                                           AS TCH_DROPS,
   -- ROUND(100 * TCH_DROPS / CSR_FAILURES, 2) AS 'WEIGHT_TCH_DROPS_IN_CELL(%)',
    ROUND(100 * SUM_TCH_DROPS           / NULLIF(SUM(SUM_TCH_DROPS)           OVER (), 0), 4)               AS 'GLOBAL_WEIGHT_TCH_DROPS(%)',

    ROUND(CSSR_HUAWEI,                      4)  AS CSSR_HUAWEI,
    ROUND(CDR_HUAWEI,                       4)  AS CDR_HUAWEI,
    ROUND(CBR_HUAWEI,                       4)  AS CBR_HUAWEI,
    ROUND(TCH_CONGESTION_RATE_HUAWEI,       4)  AS TCH_CONGESTION_RATE_HUAWEI,
    ROUND(SDCCH_CONGESTION_RATE_HUAWEI,     4)  AS SDCCH_CONGESTION_RATE_HUAWEI,
    ROUND(SDCCH_DROP_RATE_HUAWEI,           4)  AS SDCCH_DROP_RATE_HUAWEI,
    ROUND(TCH_ASSIGNMENT_SUCCESS_RATE_HUAWEI, 4) AS TCH_ASSIGNMENT_SUCCESS_RATE_HUAWEI,
    ROUND(SDCCH_TRAFFIC_HUAWEI,             4)  AS SDCCH_TRAFFIC_HUAWEI,
    ROUND(CELL_AVAILABILITY_RATE_HUAWEI,    4)  AS CELL_AVAILABILITY_RATE_HUAWEI,
    ROUND(TRAFFIC_VOIX_HUAWEI,              4)  AS TRAFFIC_VOIX_HUAWEI,
    ROUND(HANDOVER_SUCCESS_RATE_HUAWEI,     4)  AS HANDOVER_SUCCESS_RATE_HUAWEI

FROM (

    SELECT
    {select_geo}
SUM((CELL_KPI_SD_REQ - CELL_KPI_SD_SUCC) + CELL_SD_CALL_DROPS +
               (CELL_KPI_TCH_REQ_SIG + CELL_KPI_TCH_ASS_REQ_TRAF + CELL_KPI_TCH_HO_REQ_TRAF) -
               (CELL_KPI_TCH_SUCC_SIG + CELL_KPI_TCH_ASS_SUCC_TRAF + CELL_KPI_TCH_HO_SUCC_TRAF) + (CELL_KPI_TCH_DROPS_SIG+CELL_KPI_TCH_STATIC_DROPS_TRAF+CELL_KPI_TCH_HO_DROPS_TRAF)) sum_cssr_failure ,

 SUM(CELL_KPI_SD_REQ - CELL_KPI_SD_SUCC) SUM_SDCCH_ASSIGN_FAILS ,

 SUM(CELL_SD_CALL_DROPS) SUM_SDCCH_DROPS ,

 SUM((CELL_KPI_TCH_REQ_SIG + CELL_KPI_TCH_ASS_REQ_TRAF + CELL_KPI_TCH_HO_REQ_TRAF) -
               (CELL_KPI_TCH_SUCC_SIG + CELL_KPI_TCH_ASS_SUCC_TRAF + CELL_KPI_TCH_HO_SUCC_TRAF)) SUM_TCH_ASSIGN_FAILS ,

SUM((CELL_KPI_TCH_DROPS_SIG+CELL_KPI_TCH_STATIC_DROPS_TRAF+CELL_KPI_TCH_HO_DROPS_TRAF)) SUM_TCH_DROPS

   ,100 * (SUM(CELL_KPI_SD_SUCC
      ) / SUM(CELL_KPI_SD_REQ)) *
  (1 - (SUM(CELL_SD_CALL_DROPS) / SUM(CELL_KPI_SD_SUCC))) *
  (SUM(CELL_KPI_TCH_SUCC_SIG) + SUM(CELL_KPI_TCH_ASS_SUCC_TRAF) + SUM(CELL_KPI_TCH_HO_SUCC_TRAF)) /
  (SUM(CELL_KPI_TCH_REQ_SIG) + SUM(CELL_KPI_TCH_ASS_REQ_TRAF) + SUM(CELL_KPI_TCH_HO_REQ_TRAF)) *
  (1 - (((sum(CELL_KPI_TCH_DROPS_SIG)+sum(CELL_KPI_TCH_STATIC_DROPS_TRAF)+sum(CELL_KPI_TCH_HO_DROPS_TRAF))) /
    ((sum(CELL_KPI_TCH_SUCC_SIG)+sum(CELL_KPI_TCH_ASS_SUCC_TRAF)+sum(CELL_KPI_TCH_HO_SUCC_TRAF))))) AS  CSSR_HUAWEI,

      -- ARCEP 2G CALL DROP RATE - HUAWEI
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_DROPS_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_TRAF_CH_CALL_DROPS AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_DROPS_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)), 0),
        0
      ) AS CDR_HUAWEI,

      -- ARCEP 2G CALL BLOCKING RATE - HUAWEI
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_CONG_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_CONG_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_CONGEST_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_REQ_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE)), 0),
        0
      ) AS CBR_HUAWEI,

      -- TCH Congestion Rate - HUAWEI
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_CONG_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_CONGEST_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE)), 0),
        0
      ) AS TCH_CONGESTION_RATE_HUAWEI,

      -- SDCCH Congestion Rate - HUAWEI
      100.0 * COALESCE(SUM(CAST(CELL_KPI_SD_CONGEST AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CELL_KPI_SD_REQ AS DOUBLE)), 0), 0) AS SDCCH_CONGESTION_RATE_HUAWEI,

      -- SDCCH Drop Rate - HUAWEI
      100.0 * COALESCE(SUM(CAST(CELL_SD_CALL_DROPS AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CELL_IMM_ASS_SUCC_SD AS DOUBLE)), 0), 0) AS SDCCH_DROP_RATE_HUAWEI,

      -- ARCEP TCH Assignment Success Rate - HUAWEI (Vendor-specific)
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_REQ_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE)), 0),
        0
      ) AS TCH_ASSIGNMENT_SUCCESS_RATE_HUAWEI,

      -- SDCCH Traffic (Erlangs) - HUAWEI
      COALESCE(SUM(CAST(CELL_KPI_SD_TRAF_ERL AS DOUBLE)), 0) AS SDCCH_TRAFFIC_HUAWEI,

      -- 2G Availability Rate - HUAWEI
      100.0 * COALESCE(SUM(CAST(CELL_KPI_TCH_AVAIL_NUM AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CELL_KPI_TCH_CFG_NUM AS DOUBLE)), 0), 0) AS CELL_AVAILABILITY_RATE_HUAWEI,

        COALESCE(SUM(CAST(CELL_KPI_TCH_TRAF_ERL_TRAF AS DOUBLE)), 0) TRAFFIC_VOIX_HUAWEI,
        -- handover sr
        100.0 * (
  (COALESCE(SUM(CAST(CELL_INTRABSC_OUTCELL_HO_SUCC AS DOUBLE)), 0)
   + COALESCE(SUM(CAST(CELL_INTERBSC_OUTCELL_HO_SUCC AS DOUBLE)), 0))
  / NULLIF(
      COALESCE(SUM(CAST(CELL_INTRABSC_OUTCELL_HO_CMD AS DOUBLE)), 0)
      + COALESCE(SUM(CAST(CELL_INTERBSC_OUTCELL_HO_CMD AS DOUBLE)), 0),
      0
    )
) AS HANDOVER_SUCCESS_RATE_HUAWEI

    FROM hourly_huawei_2g_all_counters h
    {join_ept}
    WHERE h.date BETWEEN '{start_date}' AND '{end_date}'
    {time_filter}
    {group_by}
) AS T1
{order_by}
