-- =============================================================================
-- KPI QUERY - PUT YOUR SQL HERE
-- =============================================================================
--
-- DATE PLACEHOLDERS (REQUIRED):
--   {start_date}  - Will be replaced with start date (format: YYYY-MM-DD)
--   {end_date}    - Will be replaced with end date (format: YYYY-MM-DD)
--
-- EXAMPLE USAGE IN YOUR WHERE CLAUSE:
--   WHERE date BETWEEN '{start_date}' AND '{end_date}'
--
-- YOUR QUERY MUST RETURN THESE COLUMNS:
--   - date (DATE format)
--   - time (TIME format for hourly data)
--   - All your KPI columns as defined in config.py KPI_CHART_GROUPS
--
-- =============================================================================

-- REPLACE THIS EXAMPLE WITH YOUR ACTUAL QUERY:







WITH
  HUAWEI_2G_KPI AS (
    SELECT
      h.date
      -- h.time
      -- h.CELL_NAME,
      -- ept.SITE_NAME,
      -- ept.ARRONDISSEMENT,
      -- ept.COMMUNE,
      -- ept.DEPARTEMENT,

      
      -- CASE
      --   WHEN COALESCE(SUM(CAST(CELL_KPI_SD_REQ AS DOUBLE)), 0) = 0
      --     OR COALESCE(SUM(CAST(CELL_KPI_SD_SUCC AS DOUBLE)), 0) = 0
      --     OR (COALESCE(SUM(CAST(CELL_KPI_TCH_REQ_SIG AS DOUBLE)), 0)
      --          + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE)), 0)
      --          + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE)), 0)) = 0
      --     OR (COALESCE(SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE)), 0)
      --          + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE)), 0)
      --          + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)), 0)) = 0
      --   THEN 0
      --   ELSE
      --     100.0
      --     * (SUM(CAST(CELL_KPI_SD_SUCC AS DOUBLE))
      --         / SUM(CAST(CELL_KPI_SD_REQ AS DOUBLE)))
      --     * (1.0 - (SUM(CAST(CELL_SD_CALL_DROPS AS DOUBLE))
      --                / SUM(CAST(CELL_KPI_SD_SUCC AS DOUBLE))))
      --     * ((SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE))
      --          + SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE))
      --          + SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)))
      --         / (SUM(CAST(CELL_KPI_TCH_REQ_SIG AS DOUBLE))
      --             + SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE))
      --             + SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE))))
      --     * (1.0 - ((SUM(CAST(CELL_KPI_TCH_DROPS_SIG AS DOUBLE))
      --                 + SUM(CAST(CELL_TRAF_CH_CALL_DROPS AS DOUBLE))
      --                 + SUM(CAST(CELL_KPI_TCH_HO_DROPS_TRAF AS DOUBLE)))
      --                / (SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE))
      --                    + SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE))
      --                    + SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)))))
      -- END AS CSSR_HUAWEI
      

      ,100 * (SUM(CELL_KPI_SD_SUCC
      ) / SUM(CELL_KPI_SD_REQ)) * 
  (1 - (SUM(CELL_SD_CALL_DROPS) / SUM(CELL_KPI_SD_SUCC))) * 
  (SUM(CELL_KPI_TCH_SUCC_SIG) + SUM(CELL_KPI_TCH_ASS_SUCC_TRAF) + SUM(CELL_KPI_TCH_HO_SUCC_TRAF)) /
  (SUM(CELL_KPI_TCH_REQ_SIG) + SUM(CELL_KPI_TCH_ASS_REQ_TRAF) + SUM(CELL_KPI_TCH_HO_REQ_TRAF)) *
  (1 - (((sum(CELL_KPI_TCH_DROPS_SIG)+sum(CELL_KPI_TCH_STATIC_DROPS_TRAF)+sum(CELL_KPI_TCH_HO_DROPS_TRAF))) /
    ((sum(CELL_KPI_TCH_SUCC_SIG)+sum(CELL_KPI_TCH_ASS_SUCC_TRAF)+sum(CELL_KPI_TCH_HO_SUCC_TRAF))))) AS  CSSR_HUAWEI,

      -- ARCEP 2G CALL DROP RATE - HUAWEI
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_DROPS_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_TRAF_CH_CALL_DROPS AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_DROPS_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)), 0),
        0
      ) AS CDR_HUAWEI,

      -- ARCEP 2G CALL BLOCKING RATE - HUAWEI
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_CONG_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_CONG_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_CONGEST_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_REQ_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE)), 0),
        0
      ) AS CBR_HUAWEI,

      -- TCH Congestion Rate - HUAWEI
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_CONG_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_CONGEST_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE)), 0),
        0
      ) AS TCH_CONGESTION_RATE_HUAWEI,

      -- SDCCH Congestion Rate - HUAWEI
      100.0 * COALESCE(SUM(CAST(CELL_KPI_SD_CONGEST AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CELL_KPI_SD_REQ AS DOUBLE)), 0), 0) AS SDCCH_CONGESTION_RATE_HUAWEI,

      -- SDCCH Drop Rate - HUAWEI
      100.0 * COALESCE(SUM(CAST(CELL_SD_CALL_DROPS AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CELL_IMM_ASS_SUCC_SD AS DOUBLE)), 0), 0) AS SDCCH_DROP_RATE_HUAWEI,

      -- ARCEP TCH Assignment Success Rate - HUAWEI (Vendor-specific)
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_REQ_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE)), 0),
        0
      ) AS TCH_ASSIGNMENT_SUCCESS_RATE_HUAWEI,

      -- SDCCH Traffic (Erlangs) - HUAWEI
      COALESCE(SUM(CAST(CELL_KPI_SD_TRAF_ERL AS DOUBLE)), 0) AS SDCCH_TRAFFIC_HUAWEI,

      -- 2G Availability Rate - HUAWEI
      100.0 * COALESCE(SUM(CAST(CELL_KPI_TCH_AVAIL_NUM AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CELL_KPI_TCH_CFG_NUM AS DOUBLE)), 0), 0) AS CELL_AVAILABILITY_RATE_HUAWEI,


        COALESCE(SUM(CAST(CELL_KPI_TCH_TRAF_ERL_TRAF AS DOUBLE)), 0) TRAFFIC_VOIX_HUAWEI,
        -- handover sr
        100.0 * (
  (COALESCE(SUM(CAST(CELL_INTRABSC_OUTCELL_HO_SUCC AS DOUBLE)), 0)
   + COALESCE(SUM(CAST(CELL_INTERBSC_OUTCELL_HO_SUCC AS DOUBLE)), 0))
  / NULLIF(
      COALESCE(SUM(CAST(CELL_INTRABSC_OUTCELL_HO_CMD AS DOUBLE)), 0)
      + COALESCE(SUM(CAST(CELL_INTERBSC_OUTCELL_HO_CMD AS DOUBLE)), 0),
      0
    )
) AS HANDOVER_SUCCESS_RATE_HUAWEI



    FROM
      hourly_huawei_2g_all_counters h
    -- LEFT JOIN
    --   EPT_2G ept ON h.CELL_NAME = ept.CELL_NAME AND ept.VENDOR = 'HUAWEI'

    WHERE
      h.date BETWEEN '{start_date}' AND '{end_date}'  -- Adjust date range as needed

    GROUP BY
      h.date
      -- h.time
      -- h.CELL_NAME,
      -- ept.SITE_NAME,
      -- ept.ARRONDISSEMENT,
      -- ept.COMMUNE,
      -- ept.DEPARTEMENT
  ),

  ERICSSON_2G_KPI AS (
    SELECT
      e.DATE,
      -- e.TIME,
      -- e.CELL_NAME,
      -- ept.SITE_NAME,
      -- ept.ARRONDISSEMENT,
      -- ept.COMMUNE,
      -- ept.DEPARTEMENT,

      -- CSSR (Call Setup Success Rate) - ERICSSON
      CASE
        WHEN COALESCE(SUM(CAST(CCALLS AS DOUBLE)), 0) = 0
          OR COALESCE(SUM(CAST(CMSESTAB AS DOUBLE)), 0) = 0
          OR COALESCE(SUM(CAST(TASSALL AS DOUBLE)), 0) = 0
          OR (COALESCE(SUM(CAST(TFCASSALL AS DOUBLE)), 0)
               + COALESCE(SUM(CAST(THCASSALL AS DOUBLE)), 0)
               + COALESCE(SUM(CAST(TFCASSALLSUB AS DOUBLE)), 0)
               + COALESCE(SUM(CAST(THCASSALLSUB AS DOUBLE)), 0)
            ) = 0
        THEN 0
        ELSE
          100.0
          * (1.0 - (SUM(CAST(CCONGS AS DOUBLE))
                     / SUM(CAST(CCALLS AS DOUBLE))))
          * (1.0 - ((SUM(CAST(CNDROP AS DOUBLE))
                      - SUM(CAST(CNRELCONG AS DOUBLE)))
                     / SUM(CAST(CMSESTAB AS DOUBLE))))
          * (SUM(CAST(TCASSALL AS DOUBLE))
              / SUM(CAST(TASSALL AS DOUBLE)))
          * (1.0 - (
              (SUM(CAST(TFNDROP AS DOUBLE))
                + SUM(CAST(THNDROP AS DOUBLE))
                + SUM(CAST(TFNDROPSUB AS DOUBLE))
                + SUM(CAST(THNDROPSUB AS DOUBLE))
              )
              / (
                SUM(CAST(TFCASSALL AS DOUBLE))
                + SUM(CAST(THCASSALL AS DOUBLE))
                + SUM(CAST(TFCASSALLSUB AS DOUBLE))
                + SUM(CAST(THCASSALLSUB AS DOUBLE))
              )
            ))
      END AS CSSR_ERICSSON,

      -- Call Blocking Rate - ERICSSON (ARCEP)
      100.0 * (
        COALESCE(SUM(CAST(CNRELCONG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(TFNRELCONG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(TFNRELCONGSUB AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(THNRELCONG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(THNRELCONGSUB AS DOUBLE)), 0)
      ) / NULLIF(COALESCE(SUM(CAST(TASSALL AS DOUBLE)), 0), 0) AS CBR_ERICSSON,

      -- Call Drop Rate - ERICSSON (ARCEP)
      100.0 * (
        COALESCE(SUM(CAST(THNDROP AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(THNDROPSUB AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(TFNDROP AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(TFNDROPSUB AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(TFCASSALL AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(TFCASSALLSUB AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(THCASSALL AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(THCASSALLSUB AS DOUBLE)), 0),
        0
      ) AS CDR_ERICSSON,

      -- 2G Cell Availability Rate - ERICSSON
      100.0 - (100.0 * COALESCE(SUM(CAST(TDWNACC AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(TDWNSCAN AS DOUBLE)), 0), 0)) AS CELL_AVAILABILITY_RATE_ERICSSON,

      -- TCH Channel Availability Rate - ERICSSON (Vendor-specific)
      100.0 * (COALESCE(SUM(CAST(TAVAACC AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(TAVASCAN AS DOUBLE)), 0), 0)) /
        (COALESCE(AVG(CAST(AVG_TNUCHCNT AS DOUBLE)), 1)) AS TCH_AVAILABILITY_RATE_ERICSSON,

      -- Downtime Manual - ERICSSON (Vendor-specific)
      COALESCE(SUM(CAST(HDWNACC AS DOUBLE)), 0) AS DOWNTIME_MANUAL,

      -- TCH Congestion Rate - ERICSSON
      100.0 * (
        COALESCE(SUM(CAST(CNRELCONG AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(TFNRELCONG AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(TFNRELCONGSUB AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(THNRELCONG AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(THNRELCONGSUB AS DOUBLE)), 0)
      ) / NULLIF(COALESCE(SUM(CAST(TASSALL AS DOUBLE)), 0), 0) AS TCH_CONGESTION_RATE_ERICSSON,

      -- SDCCH Drop Rate - ERICSSON
      100.0 * COALESCE(SUM(CAST(CNDROP AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CMSESTAB AS DOUBLE)), 0), 0) AS SDCCH_DROP_RATE_ERICSSON,

      -- SDCCH Traffic - ERICSSON (Erlangs)
      COALESCE(SUM(CAST(CTRALACC AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CNSCAN AS DOUBLE)), 0), 0) AS SDCCH_TRAFFIC_ERICSSON,

      -- SDCCH Blocking Rate - ERICSSON (Vendor-specific)
      100.0 * COALESCE(SUM(CAST(CCONGS AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CCALLS AS DOUBLE)), 0), 0) AS SDCCH_BLOCKING_RATE_ERICSSON,

      -- SDCCH Congestion Rate - ERICSSON
      100.0 * (COALESCE(SUM(CAST(CCONGS AS DOUBLE)), 0) + COALESCE(SUM(CAST(CCONGSSUB AS DOUBLE)), 0)) /
        NULLIF(COALESCE(SUM(CAST(CCALLS AS DOUBLE)), 0), 0) AS SDCCH_CONGESTION_RATE_ERICSSON,

      COALESCE(SUM(CAST(TRAFFIC_DATA_GB AS DOUBLE)), 0) TRAFFIC_DATA_GB_ERICSSON,
      COALESCE(SUM(CAST(TRAFFIC_VOIX AS DOUBLE)), 0) TRAFFIC_VOIX_ERICSSON
    FROM
      hourly_ericsson_arcep_2g_counters e
    -- LEFT JOIN
    --   EPT_2G ept ON e.CELL_NAME = ept.CELL_NAME AND ept.VENDOR = 'ERICSSON'

    WHERE
      e.DATE BETWEEN '{start_date}' AND '{end_date}'  -- Adjust date range as needed

    GROUP BY
      e.DATE
      -- e.TIME
      -- e.CELL_NAME,
      -- ept.SITE_NAME,
      -- ept.ARRONDISSEMENT,
      -- ept.COMMUNE,
      -- ept.DEPARTEMENT
  )



  

SELECT
  COALESCE(h.date, e.DATE) AS date,
 -- COALESCE(h.time, e.TIME) AS time,

  -- Location Info
  -- COALESCE(h.SITE_NAME, e.SITE_NAME) AS SITE_NAME,
  -- COALESCE(h.ARRONDISSEMENT, e.ARRONDISSEMENT) AS ARRONDISSEMENT,
  -- COALESCE(h.COMMUNE, e.COMMUNE) AS COMMUNE,
  -- COALESCE(h.DEPARTEMENT, e.DEPARTEMENT) AS DEPARTEMENT,

  -- Vendor-specific KPIs
  h.CSSR_HUAWEI,
  -- h.CSSR_HUAWEI_2,
  e.CSSR_ERICSSON,
  h.CDR_HUAWEI,
  e.CDR_ERICSSON,
  h.CBR_HUAWEI,
  e.CBR_ERICSSON,
  h.TCH_CONGESTION_RATE_HUAWEI,
  e.TCH_CONGESTION_RATE_ERICSSON,
  h.SDCCH_CONGESTION_RATE_HUAWEI,
  e.SDCCH_CONGESTION_RATE_ERICSSON,
  h.SDCCH_DROP_RATE_HUAWEI,
  e.SDCCH_DROP_RATE_ERICSSON,
  h.SDCCH_TRAFFIC_HUAWEI,
  e.SDCCH_TRAFFIC_ERICSSON,
  h.CELL_AVAILABILITY_RATE_HUAWEI,
  e.CELL_AVAILABILITY_RATE_ERICSSON,

  h.TRAFFIC_VOIX_HUAWEI,
  e.TRAFFIC_VOIX_ERICSSON,

  -- Vendor-specific only
  h.TCH_ASSIGNMENT_SUCCESS_RATE_HUAWEI,
  e.TCH_AVAILABILITY_RATE_ERICSSON,
  e.DOWNTIME_MANUAL,
  e.SDCCH_BLOCKING_RATE_ERICSSON,

  h.HANDOVER_SUCCESS_RATE_HUAWEI,

  -- Network-level weighted averages (0.22 Huawei + 0.78 Ericsson)
  (COALESCE(h.CSSR_HUAWEI, 0) * 0.22) + (COALESCE(e.CSSR_ERICSSON, 0) * 0.78) AS CSSR_NETWORK,
  (COALESCE(h.CDR_HUAWEI, 0) * 0.22) + (COALESCE(e.CDR_ERICSSON, 0) * 0.78) AS CDR_NETWORK,
  (COALESCE(h.CBR_HUAWEI, 0) * 0.22) + (COALESCE(e.CBR_ERICSSON, 0) * 0.78) AS CBR_NETWORK,
  (COALESCE(h.TCH_CONGESTION_RATE_HUAWEI, 0) * 0.22) + (COALESCE(e.TCH_CONGESTION_RATE_ERICSSON, 0) * 0.78) AS TCH_CONGESTION_RATE_NETWORK,
  (COALESCE(h.SDCCH_CONGESTION_RATE_HUAWEI, 0) * 0.22) + (COALESCE(e.SDCCH_CONGESTION_RATE_ERICSSON, 0) * 0.78) AS SDCCH_CONGESTION_RATE_NETWORK,
  (COALESCE(h.SDCCH_DROP_RATE_HUAWEI, 0) * 0.22) + (COALESCE(e.SDCCH_DROP_RATE_ERICSSON, 0) * 0.78) AS SDCCH_DROP_RATE_NETWORK,
  (COALESCE(h.SDCCH_TRAFFIC_HUAWEI, 0) * 0.22) + (COALESCE(e.SDCCH_TRAFFIC_ERICSSON, 0) * 0.78) AS SDCCH_TRAFFIC_NETWORK,
  (COALESCE(h.CELL_AVAILABILITY_RATE_HUAWEI, 0) * 0.22) + (COALESCE(e.CELL_AVAILABILITY_RATE_ERICSSON, 0) * 0.78) AS CELL_AVAILABILITY_RATE_NETWORK,
  h.TRAFFIC_VOIX_HUAWEI + e.TRAFFIC_VOIX_ERICSSON AS TRAFFIC_NETWORK

FROM HUAWEI_2G_KPI h
LEFT JOIN ERICSSON_2G_KPI e
  ON h.date = e.DATE
  -- AND h.time = e.TIME

ORDER BY date
-- , time
