    SELECT
      {select_fields},

      100 * (SUM(CELL_KPI_SD_SUCC
      ) / SUM(CELL_KPI_SD_REQ)) * 
  (1 - (SUM(CELL_SD_CALL_DROPS) / SUM(CELL_KPI_SD_SUCC))) * 
  (SUM(CELL_KPI_TCH_SUCC_SIG) + SUM(CELL_KPI_TCH_ASS_SUCC_TRAF) + SUM(CELL_KPI_TCH_HO_SUCC_TRAF)) /
  (SUM(CELL_KPI_TCH_REQ_SIG) + SUM(CELL_KPI_TCH_ASS_REQ_TRAF) + SUM(CELL_KPI_TCH_HO_REQ_TRAF)) *
  (1 - (((sum(CELL_KPI_TCH_DROPS_SIG)+sum(CELL_KPI_TCH_STATIC_DROPS_TRAF)+sum(CELL_KPI_TCH_HO_DROPS_TRAF))) /
    ((sum(CELL_KPI_TCH_SUCC_SIG)+sum(CELL_KPI_TCH_ASS_SUCC_TRAF)+sum(CELL_KPI_TCH_HO_SUCC_TRAF))))) AS  CSSR_HUAWEI,

      -- ARCEP 2G CALL DROP RATE - HUAWEI
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_DROPS_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_TRAF_CH_CALL_DROPS AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_DROPS_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)), 0),
        0
      ) AS CDR_HUAWEI,

      -- ARCEP 2G CALL BLOCKING RATE - HUAWEI
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_CONG_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_CONG_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_CONGEST_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_REQ_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE)), 0),
        0
      ) AS CBR_HUAWEI,


      -- SDCCH Traffic (Erlangs) - HUAWEI
      COALESCE(SUM(CAST(CELL_KPI_SD_TRAF_ERL AS DOUBLE)), 0) AS SDCCH_TRAFFIC_HUAWEI,

      -- 2G Availability Rate - HUAWEI
      100.0 * COALESCE(SUM(CAST(CELL_KPI_TCH_AVAIL_NUM AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CELL_KPI_TCH_CFG_NUM AS DOUBLE)), 0), 0) AS CELL_AVAILABILITY_RATE_HUAWEI





    FROM
      hourly_huawei_2g_all_counters h
    LEFT JOIN
    EPT_2G ept ON h.CELL_NAME = ept.CELL_NAME AND ept.VENDOR = 'HUAWEI'

    WHERE
      {where_clause}

    GROUP BY
      {group_by}