 SELECT
      e.DATE,
      e.TIME,
      -- e.CELL_NAME,
      -- ept.SITE_NAME,
      -- ept.ARRONDISSEMENT,
      -- ept.COMMUNE,
      -- ept.DEPARTEMENT,

      -- CSSR (Call Setup Success Rate) - ERICSSON
      CASE
        WHEN COALESCE(SUM(CAST(CCALLS AS DOUBLE)), 0) = 0
          OR COALESCE(SUM(CAST(CMSESTAB AS DOUBLE)), 0) = 0
          OR COALESCE(SUM(CAST(TASSALL AS DOUBLE)), 0) = 0
          OR (COALESCE(SUM(CAST(TFCASSALL AS DOUBLE)), 0)
               + COALESCE(SUM(CAST(THCASSALL AS DOUBLE)), 0)
               + COALESCE(SUM(CAST(TFCASSALLSUB AS DOUBLE)), 0)
               + COALESCE(SUM(CAST(THCASSALLSUB AS DOUBLE)), 0)
            ) = 0
        THEN 0
        ELSE
          100.0
          * (1.0 - (SUM(CAST(CCONGS AS DOUBLE))
                     / SUM(CAST(CCALLS AS DOUBLE))))
          * (1.0 - ((SUM(CAST(CNDROP AS DOUBLE))
                      - SUM(CAST(CNRELCONG AS DOUBLE)))
                     / SUM(CAST(CMSESTAB AS DOUBLE))))
          * (SUM(CAST(TCASSALL AS DOUBLE))
              / SUM(CAST(TASSALL AS DOUBLE)))
          * (1.0 - (
              (SUM(CAST(TFNDROP AS DOUBLE))
                + SUM(CAST(THNDROP AS DOUBLE))
                + SUM(CAST(TFNDROPSUB AS DOUBLE))
                + SUM(CAST(THNDROPSUB AS DOUBLE))
              )
              / (
                SUM(CAST(TFCASSALL AS DOUBLE))
                + SUM(CAST(THCASSALL AS DOUBLE))
                + SUM(CAST(TFCASSALLSUB AS DOUBLE))
                + SUM(CAST(THCASSALLSUB AS DOUBLE))
              )
            ))
      END AS CSSR_ERICSSON,

      -- Call Blocking Rate - ERICSSON (ARCEP)
      100.0 * (
        COALESCE(SUM(CAST(CNRELCONG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(TFNRELCONG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(TFNRELCONGSUB AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(THNRELCONG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(THNRELCONGSUB AS DOUBLE)), 0)
      ) / NULLIF(COALESCE(SUM(CAST(TASSALL AS DOUBLE)), 0), 0) AS CBR_ERICSSON,

      -- Call Drop Rate - ERICSSON (ARCEP)
      100.0 * (
        COALESCE(SUM(CAST(THNDROP AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(THNDROPSUB AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(TFNDROP AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(TFNDROPSUB AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(TFCASSALL AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(TFCASSALLSUB AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(THCASSALL AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(THCASSALLSUB AS DOUBLE)), 0),
        0
      ) AS CDR_ERICSSON,

      -- 2G Cell Availability Rate - ERICSSON
      100.0 - (100.0 * COALESCE(SUM(CAST(TDWNACC AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(TDWNSCAN AS DOUBLE)), 0), 0)) AS CELL_AVAILABILITY_RATE_ERICSSON,

      -- TCH Channel Availability Rate - ERICSSON (Vendor-specific)
      100.0 * (COALESCE(SUM(CAST(TAVAACC AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(TAVASCAN AS DOUBLE)), 0), 0)) /
        (COALESCE(AVG(CAST(AVG_TNUCHCNT AS DOUBLE)), 1)) AS TCH_AVAILABILITY_RATE_ERICSSON,

      -- Downtime Manual - ERICSSON (Vendor-specific)
      COALESCE(SUM(CAST(HDWNACC AS DOUBLE)), 0) AS DOWNTIME_MANUAL,

      -- TCH Congestion Rate - ERICSSON
      100.0 * (
        COALESCE(SUM(CAST(CNRELCONG AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(TFNRELCONG AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(TFNRELCONGSUB AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(THNRELCONG AS DOUBLE)), 0) +
        COALESCE(SUM(CAST(THNRELCONGSUB AS DOUBLE)), 0)
      ) / NULLIF(COALESCE(SUM(CAST(TASSALL AS DOUBLE)), 0), 0) AS TCH_CONGESTION_RATE_ERICSSON,

      -- SDCCH Drop Rate - ERICSSON
      100.0 * COALESCE(SUM(CAST(CNDROP AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CMSESTAB AS DOUBLE)), 0), 0) AS SDCCH_DROP_RATE_ERICSSON,

      -- SDCCH Traffic - ERICSSON (Erlangs)
      COALESCE(SUM(CAST(CTRALACC AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CNSCAN AS DOUBLE)), 0), 0) AS SDCCH_TRAFFIC_ERICSSON,

      -- SDCCH Blocking Rate - ERICSSON (Vendor-specific)
      100.0 * COALESCE(SUM(CAST(CCONGS AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CCALLS AS DOUBLE)), 0), 0) AS SDCCH_BLOCKING_RATE_ERICSSON,

      -- SDCCH Congestion Rate - ERICSSON
      100.0 * (COALESCE(SUM(CAST(CCONGS AS DOUBLE)), 0) + COALESCE(SUM(CAST(CCONGSSUB AS DOUBLE)), 0)) /
        NULLIF(COALESCE(SUM(CAST(CCALLS AS DOUBLE)), 0), 0) AS SDCCH_CONGESTION_RATE_ERICSSON,

      COALESCE(SUM(CAST(TRAFFIC_DATA_GB AS DOUBLE)), 0) TRAFFIC_DATA_GB_ERICSSON,
      COALESCE(SUM(CAST(TRAFFIC_VOIX AS DOUBLE)), 0) TRAFFIC_VOIX_ERICSSON
  -- ,CASE
 --  WHEN SUM(CAST(TDWNSCAN AS DOUBLE)) < 8642
 --  THEN SUM(CAST(TDWNACC AS DOUBLE)) * 10
 --  ELSE SUM(CAST(TDWNACC AS DOUBLE)) * 86400.0 / SUM(CAST(TDWNSCAN AS DOUBLE)) 
  -- END downtime_sec
    FROM
      hourly_ericsson_arcep_2g_counters e
    -- LEFT JOIN
    --   EPT_2G ept ON e.CELL_NAME = ept.CELL_NAME AND ept.VENDOR = 'ERICSSON'

    WHERE
      e.DATE BETWEEN '2026-01-28' AND '2026-01-29'  -- Adjust date range as needed

    GROUP BY
      e.DATE,
      e.TIME
      -- e.CELL_NAME,
      -- ept.SITE_NAME,
      -- ept.ARRONDISSEMENT,
      -- ept.COMMUNE,
      -- ept.DEPARTEMENT