 SELECT
      h.date,
      h.time
      -- h.CELL_NAME,
      -- ept.SITE_NAME,
      -- ept.ARRONDISSEMENT,
      -- ept.COMMUNE,
      -- ept.DEPARTEMENT,

      
      -- CASE
      --   WHEN COALESCE(SUM(CAST(CELL_KPI_SD_REQ AS DOUBLE)), 0) = 0
      --     OR COALESCE(SUM(CAST(CELL_KPI_SD_SUCC AS DOUBLE)), 0) = 0
      --     OR (COALESCE(SUM(CAST(CELL_KPI_TCH_REQ_SIG AS DOUBLE)), 0)
      --          + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE)), 0)
      --          + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE)), 0)) = 0
      --     OR (COALESCE(SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE)), 0)
      --          + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE)), 0)
      --          + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)), 0)) = 0
      --   THEN 0
      --   ELSE
      --     100.0
      --     * (SUM(CAST(CELL_KPI_SD_SUCC AS DOUBLE))
      --         / SUM(CAST(CELL_KPI_SD_REQ AS DOUBLE)))
      --     * (1.0 - (SUM(CAST(CELL_SD_CALL_DROPS AS DOUBLE))
      --                / SUM(CAST(CELL_KPI_SD_SUCC AS DOUBLE))))
      --     * ((SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE))
      --          + SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE))
      --          + SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)))
      --         / (SUM(CAST(CELL_KPI_TCH_REQ_SIG AS DOUBLE))
      --             + SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE))
      --             + SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE))))
      --     * (1.0 - ((SUM(CAST(CELL_KPI_TCH_DROPS_SIG AS DOUBLE))
      --                 + SUM(CAST(CELL_TRAF_CH_CALL_DROPS AS DOUBLE))
      --                 + SUM(CAST(CELL_KPI_TCH_HO_DROPS_TRAF AS DOUBLE)))
      --                / (SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE))
      --                    + SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE))
      --                    + SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)))))
      -- END AS CSSR_HUAWEI
      

      ,100 * (SUM(CELL_KPI_SD_SUCC
      ) / SUM(CELL_KPI_SD_REQ)) * 
  (1 - (SUM(CELL_SD_CALL_DROPS) / SUM(CELL_KPI_SD_SUCC))) * 
  (SUM(CELL_KPI_TCH_SUCC_SIG) + SUM(CELL_KPI_TCH_ASS_SUCC_TRAF) + SUM(CELL_KPI_TCH_HO_SUCC_TRAF)) /
  (SUM(CELL_KPI_TCH_REQ_SIG) + SUM(CELL_KPI_TCH_ASS_REQ_TRAF) + SUM(CELL_KPI_TCH_HO_REQ_TRAF)) *
  (1 - (((sum(CELL_KPI_TCH_DROPS_SIG)+sum(CELL_KPI_TCH_STATIC_DROPS_TRAF)+sum(CELL_KPI_TCH_HO_DROPS_TRAF))) /
    ((sum(CELL_KPI_TCH_SUCC_SIG)+sum(CELL_KPI_TCH_ASS_SUCC_TRAF)+sum(CELL_KPI_TCH_HO_SUCC_TRAF))))) AS  CSSR_HUAWEI,

      -- ARCEP 2G CALL DROP RATE - HUAWEI
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_DROPS_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_TRAF_CH_CALL_DROPS AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_DROPS_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)), 0),
        0
      ) AS CDR_HUAWEI,

      -- ARCEP 2G CALL BLOCKING RATE - HUAWEI
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_CONG_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_CONG_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_CONGEST_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_REQ_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE)), 0),
        0
      ) AS CBR_HUAWEI,

      -- TCH Congestion Rate - HUAWEI
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_CONG_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_CONGEST_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE)), 0),
        0
      ) AS TCH_CONGESTION_RATE_HUAWEI,

      -- SDCCH Congestion Rate - HUAWEI
      100.0 * COALESCE(SUM(CAST(CELL_KPI_SD_CONGEST AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CELL_KPI_SD_REQ AS DOUBLE)), 0), 0) AS SDCCH_CONGESTION_RATE_HUAWEI,

      -- SDCCH Drop Rate - HUAWEI
      100.0 * COALESCE(SUM(CAST(CELL_SD_CALL_DROPS AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CELL_IMM_ASS_SUCC_SD AS DOUBLE)), 0), 0) AS SDCCH_DROP_RATE_HUAWEI,

      -- ARCEP TCH Assignment Success Rate - HUAWEI (Vendor-specific)
      100.0 * (
        COALESCE(SUM(CAST(CELL_KPI_TCH_SUCC_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_SUCC_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_SUCC_TRAF AS DOUBLE)), 0)
      ) / NULLIF(
        COALESCE(SUM(CAST(CELL_KPI_TCH_REQ_SIG AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_ASS_REQ_TRAF AS DOUBLE)), 0)
        + COALESCE(SUM(CAST(CELL_KPI_TCH_HO_REQ_TRAF AS DOUBLE)), 0),
        0
      ) AS TCH_ASSIGNMENT_SUCCESS_RATE_HUAWEI,

      -- SDCCH Traffic (Erlangs) - HUAWEI
      COALESCE(SUM(CAST(CELL_KPI_SD_TRAF_ERL AS DOUBLE)), 0) AS SDCCH_TRAFFIC_HUAWEI,

      -- 2G Availability Rate - HUAWEI
      100.0 * COALESCE(SUM(CAST(CELL_KPI_TCH_AVAIL_NUM AS DOUBLE)), 0) /
        NULLIF(COALESCE(SUM(CAST(CELL_KPI_TCH_CFG_NUM AS DOUBLE)), 0), 0) AS CELL_AVAILABILITY_RATE_HUAWEI,


        COALESCE(SUM(CAST(CELL_KPI_TCH_TRAF_ERL_TRAF AS DOUBLE)), 0) TRAFFIC_VOIX_HUAWEI,
        -- handover sr
        100.0 * (
  (COALESCE(SUM(CAST(CELL_INTRABSC_OUTCELL_HO_SUCC AS DOUBLE)), 0)
   + COALESCE(SUM(CAST(CELL_INTERBSC_OUTCELL_HO_SUCC AS DOUBLE)), 0))
  / NULLIF(
      COALESCE(SUM(CAST(CELL_INTRABSC_OUTCELL_HO_CMD AS DOUBLE)), 0)
      + COALESCE(SUM(CAST(CELL_INTERBSC_OUTCELL_HO_CMD AS DOUBLE)), 0),
      0
    )
) AS HANDOVER_SUCCESS_RATE_HUAWEI



    FROM
      hourly_huawei_2g_all_counters h
        LEFT JOIN
        EPT_2G ept ON h.CELL_NAME = ept.CELL_NAME AND ept.VENDOR = 'HUAWEI'

    WHERE
    
      h.date BETWEEN '2026-01-19' AND '2026-01-25'  -- Adjust date range as needed

    GROUP BY
      h.date,
      h.time
      -- h.CELL_NAME,
      -- ept.SITE_NAME,
      -- ept.ARRONDISSEMENT,
      -- ept.COMMUNE,
      -- ept.DEPARTEMENT