SELECT
    e.DATE AS date{time_select},

    -- CSSR (Call Setup Success Rate) - ERICSSON
    CASE
      WHEN COALESCE(SUM(CAST(CCALLS AS DOUBLE)), 0) = 0
        OR COALESCE(SUM(CAST(CMSESTAB AS DOUBLE)), 0) = 0
        OR COALESCE(SUM(CAST(TASSALL AS DOUBLE)), 0) = 0
        OR (COALESCE(SUM(CAST(TFCASSALL AS DOUBLE)), 0)
             + COALESCE(SUM(CAST(THCASSALL AS DOUBLE)), 0)
             + COALESCE(SUM(CAST(TFCASSALLSUB AS DOUBLE)), 0)
             + COALESCE(SUM(CAST(THCASSALLSUB AS DOUBLE)), 0)
          ) = 0
      THEN 0
      ELSE
        100.0
        * (1.0 - (SUM(CAST(CCONGS AS DOUBLE))
                   / SUM(CAST(CCALLS AS DOUBLE))))
        * (1.0 - ((SUM(CAST(CNDROP AS DOUBLE))
                    - SUM(CAST(CNRELCONG AS DOUBLE)))
                   / SUM(CAST(CMSESTAB AS DOUBLE))))
        * (SUM(CAST(TCASSALL AS DOUBLE))
            / SUM(CAST(TASSALL AS DOUBLE)))
        * (1.0 - (
            (SUM(CAST(TFNDROP AS DOUBLE))
              + SUM(CAST(THNDROP AS DOUBLE))
              + SUM(CAST(TFNDROPSUB AS DOUBLE))
              + SUM(CAST(THNDROPSUB AS DOUBLE))
            )
            / (
              SUM(CAST(TFCASSALL AS DOUBLE))
              + SUM(CAST(THCASSALL AS DOUBLE))
              + SUM(CAST(TFCASSALLSUB AS DOUBLE))
              + SUM(CAST(THCASSALLSUB AS DOUBLE))
            )
          ))
    END AS CSSR_ERICSSON,

    -- Call Blocking Rate - ERICSSON
    100.0 * (
      COALESCE(SUM(CAST(CNRELCONG AS DOUBLE)), 0)
      + COALESCE(SUM(CAST(TFNRELCONG AS DOUBLE)), 0)
      + COALESCE(SUM(CAST(TFNRELCONGSUB AS DOUBLE)), 0)
      + COALESCE(SUM(CAST(THNRELCONG AS DOUBLE)), 0)
      + COALESCE(SUM(CAST(THNRELCONGSUB AS DOUBLE)), 0)
    ) / NULLIF(COALESCE(SUM(CAST(TASSALL AS DOUBLE)), 0), 0) AS CBR_ERICSSON,

    -- Call Drop Rate - ERICSSON
    100.0 * (
      COALESCE(SUM(CAST(THNDROP AS DOUBLE)), 0) +
      COALESCE(SUM(CAST(THNDROPSUB AS DOUBLE)), 0) +
      COALESCE(SUM(CAST(TFNDROP AS DOUBLE)), 0) +
      COALESCE(SUM(CAST(TFNDROPSUB AS DOUBLE)), 0)
    ) / NULLIF(
      COALESCE(SUM(CAST(TFCASSALL AS DOUBLE)), 0) +
      COALESCE(SUM(CAST(TFCASSALLSUB AS DOUBLE)), 0) +
      COALESCE(SUM(CAST(THCASSALL AS DOUBLE)), 0) +
      COALESCE(SUM(CAST(THCASSALLSUB AS DOUBLE)), 0),
      0
    ) AS CDR_ERICSSON,

    -- Cell Availability Rate - ERICSSON
    100.0 - (100.0 * COALESCE(SUM(CAST(TDWNACC AS DOUBLE)), 0) /
      NULLIF(COALESCE(SUM(CAST(TDWNSCAN AS DOUBLE)), 0), 0)) AS CELL_AVAILABILITY_RATE_ERICSSON,

    -- TCH Channel Availability Rate - ERICSSON
    100.0 * (COALESCE(SUM(CAST(TAVAACC AS DOUBLE)), 0) /
      NULLIF(COALESCE(SUM(CAST(TAVASCAN AS DOUBLE)), 0), 0)) /
      (COALESCE(AVG(CAST(AVG_TNUCHCNT AS DOUBLE)), 1)) AS TCH_AVAILABILITY_RATE_ERICSSON,

    -- Downtime Manual - ERICSSON
    COALESCE(SUM(CAST(HDWNACC AS DOUBLE)), 0) AS DOWNTIME_MANUAL,

    -- TCH Congestion Rate - ERICSSON
    100.0 * (
      COALESCE(SUM(CAST(CNRELCONG AS DOUBLE)), 0) +
      COALESCE(SUM(CAST(TFNRELCONG AS DOUBLE)), 0) +
      COALESCE(SUM(CAST(TFNRELCONGSUB AS DOUBLE)), 0) +
      COALESCE(SUM(CAST(THNRELCONG AS DOUBLE)), 0) +
      COALESCE(SUM(CAST(THNRELCONGSUB AS DOUBLE)), 0)
    ) / NULLIF(COALESCE(SUM(CAST(TASSALL AS DOUBLE)), 0), 0) AS TCH_CONGESTION_RATE_ERICSSON,

    -- SDCCH Drop Rate - ERICSSON
    100.0 * COALESCE(SUM(CAST(CNDROP AS DOUBLE)), 0) /
      NULLIF(COALESCE(SUM(CAST(CMSESTAB AS DOUBLE)), 0), 0) AS SDCCH_DROP_RATE_ERICSSON,

    -- SDCCH Traffic - ERICSSON (Erlangs)
    COALESCE(SUM(CAST(CTRALACC AS DOUBLE)), 0) /
      NULLIF(COALESCE(SUM(CAST(CNSCAN AS DOUBLE)), 0), 0) AS SDCCH_TRAFFIC_ERICSSON,

    -- SDCCH Blocking Rate - ERICSSON
    100.0 * COALESCE(SUM(CAST(CCONGS AS DOUBLE)), 0) /
      NULLIF(COALESCE(SUM(CAST(CCALLS AS DOUBLE)), 0), 0) AS SDCCH_BLOCKING_RATE_ERICSSON,

    -- SDCCH Congestion Rate - ERICSSON
    100.0 * (COALESCE(SUM(CAST(CCONGS AS DOUBLE)), 0) + COALESCE(SUM(CAST(CCONGSSUB AS DOUBLE)), 0)) /
      NULLIF(COALESCE(SUM(CAST(CCALLS AS DOUBLE)), 0), 0) AS SDCCH_CONGESTION_RATE_ERICSSON,

    -- Traffic Data - ERICSSON
    COALESCE(SUM(CAST(TRAFFIC_DATA_GB AS DOUBLE)), 0) AS TRAFFIC_DATA_GB_ERICSSON,

    -- Traffic Voice - ERICSSON
    COALESCE(SUM(CAST(TRAFFIC_VOIX AS DOUBLE)), 0) AS TRAFFIC_VOIX_ERICSSON

FROM
    hourly_ericsson_arcep_2g_counters e

WHERE
    {date_filter}
    {cell_filter}

GROUP BY
    e.DATE{time_group}

ORDER BY
    e.DATE{time_group}
