-- MySQL table : hourly_huawei_2g_all_counters
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_huawei_2g_all_counters (
    date                                     DATE  NOT NULL,
    time                                     TIME  NOT NULL,
    GCELL                                    VARCHAR  NULL,
    CELL_NAME                                VARCHAR  NOT NULL,
    controller_name                          VARCHAR  NULL,
    cell_index                               VARCHAR  NULL,
    CGI                                      VARCHAR  NULL,
    CELL_SERV_OOS                            DECIMAL(38, 12)  NULL,
    CELL_TRAF_CH_CALL_DROPS                  DECIMAL(38, 12)  NULL,
    CELL_TRAF_CH_CALL_DROPS_IN_STABLE_STATE  DECIMAL(38, 12)  NULL,
    CELL_TRAF_CH_CALL_DROPS_HO_FAIL          DECIMAL(38, 12)  NULL,
    CELL_TRAF_CH_CALL_DROPS_ABIS_LNK_FAIL    DECIMAL(38, 12)  NULL,
    CELL_TRAF_CH_CALL_DROPS_EQUIP_FAIL       DECIMAL(38, 12)  NULL,
    CELL_TRAF_CH_CALL_DROPS_FORCE_HO         DECIMAL(38, 12)  NULL,
    CELL_SD_CALL_DROPS                       DECIMAL(38, 12)  NULL,
    CELL_IMM_ASS_SUCC_SD                     DECIMAL(38, 12)  NULL,
    CELL_INTRABSC_OUTCELL_HO_SUCC            DECIMAL(38, 12)  NULL,
    CELL_INTRABSC_OUTCELL_HO_CMD             DECIMAL(38, 12)  NULL,
    CELL_INTERBSC_OUTCELL_HO_SUCC            DECIMAL(38, 12)  NULL,
    CELL_INTERBSC_OUTCELL_HO_CMD             DECIMAL(38, 12)  NULL,
    CELL_KPI_SD_REQ                          DECIMAL(38, 12)  NULL,
    CELL_KPI_SD_CONGEST                      DECIMAL(38, 12)  NULL,
    CELL_KPI_SD_SUCC                         DECIMAL(38, 12)  NULL,
    CELL_KPI_SD_TRAF_ERL                     DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_REQ_SIG                     DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_CONG_SIG                    DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_SUCC_SIG                    DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_DROPS_SIG                   DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_ASS_REQ_TRAF                DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_ASS_CONG_TRAF               DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_ASS_SUCC_TRAF               DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_STATIC_DROPS_TRAF           DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_HO_REQ_TRAF                 DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_HO_CONGEST_TRAF             DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_HO_SUCC_TRAF                DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_HO_DROPS_TRAF               DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_TRAF_ERL_TRAF               DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_AVAIL_NUM                   DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_CFG_NUM                     DECIMAL(38, 12)  NULL,
    CELL_KPI_TCHH_TRAF_ERL                   DECIMAL(38, 12)  NULL,
    CELL_KPI_TCH_CONGESTION_RATE             DECIMAL(38, 12)  NULL,
    CELL_SD_CALL_DROPS_CALL                  DECIMAL(38, 12)  NULL,
    CELL_SD_UM_CALL_DROPS_CALL               DECIMAL(38, 12)  NULL,
    CELL_SD_CALL_DROPS_TA                    DECIMAL(38, 12)  NULL,
    CELL_SD_CALL_DROPS_RCV_LEVEL             DECIMAL(38, 12)  NULL,
    CELL_SD_CALL_DROPS_QUAL                  DECIMAL(38, 12)  NULL,
    CELL_SD_CALL_DROPS_OTHER                 DECIMAL(38, 12)  NULL,
    CELL_RATE_SD_CONG                        DECIMAL(38, 12)  NULL,
    CELL_TCH_CALL_DROPS_TA                   DECIMAL(38, 12)  NULL,
    CELL_TCH_CALL_DROPS_UL_RCV_LEVEL         DECIMAL(38, 12)  NULL,
    CELL_TCH_CALL_DROPS_DL_RCV_LEVEL         DECIMAL(38, 12)  NULL,
    CELL_TCH_CALL_DROPS_ULDL_RCV_LEVEL       DECIMAL(38, 12)  NULL,
    CELL_TCH_CALL_DROPS_UL_FER               DECIMAL(38, 12)  NULL,
    CELL_TCH_CALL_DROPS_DL_FER               DECIMAL(38, 12)  NULL,
    CELL_TCH_CALL_DROPS_ULDL_FER             DECIMAL(38, 12)  NULL,
    CELL_TCH_CALL_DROPS_UL_QUAL              DECIMAL(38, 12)  NULL,
    CELL_TCH_CALL_DROPS_DL_QUAL              DECIMAL(38, 12)  NULL,
    CELL_TCH_CALL_DROPS_ULDL_QUAL            DECIMAL(38, 12)  NULL,
    CELL_TCH_CALL_DROPS_OTHER                DECIMAL(38, 12)  NULL,
    CELL_SERV_OOS_OM                         DECIMAL(38, 12)  NULL,
    CELL_SD_CALL_DROPS_LOC_UPDATE            DECIMAL(38, 12)  NULL,
    PRIMARY KEY (date, time, CELL_NAME)
);

-- MySQL table : hourly_huawei_3g_all_counters_1
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_huawei_3g_all_counters_1 (
    date                                     DATE  NOT NULL,
    time                                     TIME  NOT NULL,
    GCELL                                    VARCHAR  NULL,
    CELL_NAME                                VARCHAR  NOT NULL,
    controller_name                          VARCHAR  NULL,
    Cell_Index                               VARCHAR  NULL,
    LogicRNCID                               VARCHAR  NULL,
    RRC_AttConnEstab_OrgConvCall             DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_OrgStrCall              DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_OrgInterCall            DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_OrgBkgCall              DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_OrgSubCall              DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_TmConvCall              DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_TmStrCall               DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_TmInterCall             DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_TmBkgCall               DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_EmgCall                 DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_OrgHhPrSig              DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_OrgLwPrSig              DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_CallReEst               DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_TmHhPrSig               DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_TmLwPrSig               DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_Unknown                 DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_OrgConvCall            DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_OrgSubCall             DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_TmConvCall             DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_EmgCall                DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_CallReEst              DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_Unkown                 DECIMAL(38, 12)  NULL,
    VS_RRC_Rej_Code_Cong                     DECIMAL(38, 12)  NULL,
    VS_RRC_Rej_DLCE_Cong                     DECIMAL(38, 12)  NULL,
    VS_RRC_Rej_DLPower_Cong                  DECIMAL(38, 12)  NULL,
    VS_RAB_NormRel_CS                        DECIMAL(38, 12)  NULL,
    VS_RAB_NormRel_PS                        DECIMAL(38, 12)  NULL,
    VS_RAB_NormRel_CS_HSPA_Conv              DECIMAL(38, 12)  NULL,
    VS_RAB_NormRel_AMRWB                     DECIMAL(38, 12)  NULL,
    VS_RAB_NormRel_PS_PCH                    DECIMAL(38, 12)  NULL,
    VS_RAB_AbnormRel_PS                      DECIMAL(38, 12)  NULL,
    VS_RAB_AbnormRel_AMR                     DECIMAL(38, 12)  NULL,
    VS_RAB_AbnormRel_CS_HSPA_Conv            DECIMAL(38, 12)  NULL,
    VS_RAB_AbnormRel_AMRWB                   DECIMAL(38, 12)  NULL,
    VS_RAB_AbnormRel_PS_PCH                  DECIMAL(38, 12)  NULL,
    VS_RAB_AbnormRel_PS_F2P                  DECIMAL(38, 12)  NULL,
    VS_RAB_AbnormRel_PS_D2P                  DECIMAL(38, 12)  NULL,
    VS_RAB_AttEstabCS_Conv                   DECIMAL(38, 12)  NULL,
    VS_RAB_AttEstabCS_Str                    DECIMAL(38, 12)  NULL,
    VS_RAB_AttEstab_AMR                      DECIMAL(38, 12)  NULL,
    VS_RAB_AttEstabCS_AMRWB                  DECIMAL(38, 12)  NULL,
    VS_RAB_SuccEstabCS_Conv                  DECIMAL(38, 12)  NULL,
    VS_RAB_SuccEstabCS_Str                   DECIMAL(38, 12)  NULL,
    VS_RAB_SuccEstabCS_AMR                   DECIMAL(38, 12)  NULL,
    VS_RAB_SuccEstabCS_AMRWB                 DECIMAL(38, 12)  NULL,
    VS_RAB_FailEstabCS_Code_Cong             DECIMAL(38, 12)  NULL,
    VS_RAB_FailEstabCS_DLCE_Cong             DECIMAL(38, 12)  NULL,
    VS_RAB_FailEstabCS_ULCE_Cong             DECIMAL(38, 12)  NULL,
    VS_RAB_FailEstabCS_ULIUBBand_Cong        DECIMAL(38, 12)  NULL,
    VS_RAB_FailEstabCS_DLIUBBand_Cong        DECIMAL(38, 12)  NULL,
    VS_RAB_FailEstabCS_ULPower_Cong          DECIMAL(38, 12)  NULL,
    VS_RAB_FailEstabCS_DLPower_Cong          DECIMAL(38, 12)  NULL,
    VS_RAB_FailEstabPS_Code_Cong             DECIMAL(38, 12)  NULL,
    VS_RAB_FailEstabPS_DLCE_Cong             DECIMAL(38, 12)  NULL,
    VS_HSPA_RAB_AttEstab_CS_Conv             DECIMAL(38, 12)  NULL,
    VS_HSPA_RAB_SuccEstab_CS_Conv            DECIMAL(38, 12)  NULL,
    VS_DCCC_Succ_F2P                         DECIMAL(38, 12)  NULL,
    VS_DCCC_D2P_Succ                         DECIMAL(38, 12)  NULL,
    VS_Cell_UnavailTime_Sys                  DECIMAL(38, 12)  NULL,
    Total_PS_Traffic_GB                      DECIMAL(38, 12)  NULL,
    PRIMARY KEY (date, time, CELL_NAME)
);

-- MySQL table : hourly_huawei_3g_all_counters_2
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_huawei_3g_all_counters_2 (
    date                                     DATE  NOT NULL,
    time                                     TIME  NOT NULL,
    GCELL                                    VARCHAR  NULL,
    CELL_NAME                                VARCHAR  NOT NULL,
    controller_name                          VARCHAR  NULL,
    Cell_Index                               VARCHAR  NULL,
    LogicRNCID                               VARCHAR  NULL,
    RRC_AttConnEstab_OrgStrCall              DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_OrgInterCall            DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_OrgBkgCall              DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_OrgSubCall              DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_TmStrCall               DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_TmInterCall             DECIMAL(38, 12)  NULL,
    RRC_AttConnEstab_TmBkgCall               DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_OrgStrCall             DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_OrgInterCall           DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_OrgBkgCall             DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_OrgSubCall             DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_TmStrCall              DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_TmItrCall              DECIMAL(38, 12)  NULL,
    RRC_SuccConnEstab_TmBkgCall              DECIMAL(38, 12)  NULL,
    VS_RAB_AttEstabPS_Conv                   DECIMAL(38, 12)  NULL,
    VS_RAB_AttEstabPS_Str                    DECIMAL(38, 12)  NULL,
    VS_RAB_AttEstabPS_Int                    DECIMAL(38, 12)  NULL,
    VS_RAB_AttEstabPS_Bkg                    DECIMAL(38, 12)  NULL,
    VS_RAB_SuccEstabPS_Conv                  DECIMAL(38, 12)  NULL,
    VS_RAB_SuccEstabPS_Str                   DECIMAL(38, 12)  NULL,
    VS_RAB_SuccEstabPS_Int                   DECIMAL(38, 12)  NULL,
    VS_RAB_SuccEstabPS_Bkg                   DECIMAL(38, 12)  NULL,
    VS_SHO_AttRLAdd                          DECIMAL(38, 12)  NULL,
    VS_SHO_SuccRLAdd                         DECIMAL(38, 12)  NULL,
    VS_SHO_AttRLDel                          DECIMAL(38, 12)  NULL,
    VS_SHO_SuccRLDel                         DECIMAL(38, 12)  NULL,
    IRATHO_AttOutCS                          DECIMAL(38, 12)  NULL,
    IRATHO_SuccOutCS                         DECIMAL(38, 12)  NULL,
    VS_AMR_Erlang_BestCell                   DECIMAL(38, 12)  NULL,
    VS_RRC_AttConnEstab_EDCH                 DECIMAL(38, 12)  NULL,
    VS_RRC_AttConnEstab_HSDSCH               DECIMAL(38, 12)  NULL,
    VS_RRC_SuccConnEstab_EDCH                DECIMAL(38, 12)  NULL,
    VS_RRC_SuccConnEstab_HSDSCH              DECIMAL(38, 12)  NULL,
    VS_HSDPA_MeanChThroughput                DECIMAL(38, 12)  NULL,
    VS_HSUPA_MeanChThroughput                DECIMAL(38, 12)  NULL,
    PRIMARY KEY (date, time, CELL_NAME)
);

-- MySQL table :    
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_huawei_3g_packet_loss (
    date                                     DATE  NOT NULL,
    time                                     TIME  NOT NULL,
    controller_name                          VARCHAR  NOT NULL,
    adjacent_node_id                         VARCHAR  NOT NULL,
    phb                                      VARCHAR  NOT NULL,
    local_ip                                 VARCHAR  NULL,
    peer_ip                                  VARCHAR  NULL,
    VS_IPPOOL_IPPM_Local_TxPkts              DECIMAL(38, 12)  NULL,
    VS_IPPOOL_IPPM_Peer_RxPkts               DECIMAL(38, 12)  NULL,
    VS_IPPOOL_IPPM_Forward_DropMeans         DECIMAL(38, 12)  NULL,
    PRIMARY KEY (date, time, controller_name, adjacent_node_id, phb)
);

-- MySQL table : hourly_huawei_4g_all_counters_1
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_huawei_4g_all_counters_1 (
    date                                     DATE  NOT NULL,
    time                                     TIME  NOT NULL,
    GCELL                                    VARCHAR  NULL,
    SITE_NAME                                VARCHAR  NULL,
    CELL_NAME                                VARCHAR  NOT NULL,
    eNodeB_Func_Name                         VARCHAR  NULL,
    eNodeB_ID                                VARCHAR  NULL,
    local_cell_id                            VARCHAR  NULL,
    L_HHO_IntraeNB_IntraFreq_PrepAttOut      DECIMAL(38, 12)  NULL,
    L_HHO_IntraeNB_IntraFreq_ExecAttOut      DECIMAL(38, 12)  NULL,
    L_HHO_IntraeNB_IntraFreq_ExecSuccOut     DECIMAL(38, 12)  NULL,
    L_HHO_IntraeNB_InterFreq_PrepAttOut      DECIMAL(38, 12)  NULL,
    L_HHO_IntraeNB_InterFreq_ExecAttOut      DECIMAL(38, 12)  NULL,
    L_HHO_IntraeNB_InterFreq_ExecSuccOut     DECIMAL(38, 12)  NULL,
    L_HHO_IntereNB_IntraFreq_PrepAttOut      DECIMAL(38, 12)  NULL,
    L_HHO_IntereNB_IntraFreq_ExecAttOut      DECIMAL(38, 12)  NULL,
    L_HHO_IntereNB_IntraFreq_ExecSuccOut     DECIMAL(38, 12)  NULL,
    L_HHO_IntereNB_InterFreq_PrepAttOut      DECIMAL(38, 12)  NULL,
    L_HHO_IntereNB_InterFreq_ExecAttOut      DECIMAL(38, 12)  NULL,
    L_HHO_IntereNB_InterFreq_ExecSuccOut     DECIMAL(38, 12)  NULL,
    L_HHO_IntereNB_InterFddTdd_PrepAttOut    DECIMAL(38, 12)  NULL,
    L_HHO_IntereNB_InterFddTdd_ExecAttOut    DECIMAL(38, 12)  NULL,
    L_HHO_IntereNB_InterFddTdd_ExecSuccOut   DECIMAL(38, 12)  NULL,
    L_Cell_Unavail_Dur_Sys                   DECIMAL(38, 12)  NULL,
    L_Cell_Unavail_Dur_Manual                DECIMAL(38, 12)  NULL,
    L_E_RAB_SuccEst                          DECIMAL(38, 12)  NULL,
    L_E_RAB_AttEst                           DECIMAL(38, 12)  NULL,
    L_E_RAB_AbnormRel                        DECIMAL(38, 12)  NULL,
    L_E_RAB_NormRel                          DECIMAL(38, 12)  NULL,
    L_RRC_ConnReq_Att_Emc                    DECIMAL(38, 12)  NULL,
    L_RRC_ConnReq_Att_HighPri                DECIMAL(38, 12)  NULL,
    L_RRC_ConnReq_Att_Mt                     DECIMAL(38, 12)  NULL,
    L_RRC_ConnReq_Att_MoData                 DECIMAL(38, 12)  NULL,
    L_RRC_ConnReq_Succ_Emc                   DECIMAL(38, 12)  NULL,
    L_RRC_ConnReq_Succ_HighPri               DECIMAL(38, 12)  NULL,
    L_RRC_ConnReq_Succ_Mt                    DECIMAL(38, 12)  NULL,
    L_RRC_ConnReq_Succ_MoData                DECIMAL(38, 12)  NULL,
    L_Thrp_bits_UL                           DECIMAL(38, 12)  NULL,
    L_Thrp_bits_DL                           DECIMAL(38, 12)  NULL,
    L_Thrp_bits_DL_LastTTI                   DECIMAL(38, 12)  NULL,
    L_Thrp_bits_UE_UL_LastTTI                DECIMAL(38, 12)  NULL,
    L_Thrp_Time_Cell_DL_HighPrecision        DECIMAL(38, 12)  NULL,
    L_Thrp_Time_Cell_UL_HighPrecision        DECIMAL(38, 12)  NULL,
    L_Thrp_Time_DL_RmvLastTTI                DECIMAL(38, 12)  NULL,
    L_Thrp_Time_UE_UL_RmvLastTTI             DECIMAL(38, 12)  NULL,
    L_CSFB_PrepAtt                           DECIMAL(38, 12)  NULL,
    L_CSFB_PrepSucc                          DECIMAL(38, 12)  NULL,
    L_CSFB_E2W                               DECIMAL(38, 12)  NULL,
    L_CSFB_E2G                               DECIMAL(38, 12)  NULL,
    L_RRCRedirection_E2W_CSFB                DECIMAL(38, 12)  NULL,
    L_RRCRedirection_E2G_CSFB                DECIMAL(38, 12)  NULL,
    L_IRATHO_E2W_CSFB_ExecAttOut             DECIMAL(38, 12)  NULL,
    L_IRATHO_E2W_CSFB_ExecSuccOut            DECIMAL(38, 12)  NULL,
    L_IRATHO_E2G_CSFB_ExecAttOut             DECIMAL(38, 12)  NULL,
    L_IRATHO_E2G_CSFB_ExecSuccOut            DECIMAL(38, 12)  NULL,
    TOTAL_DATA_GBITS                         DECIMAL(38, 12)  NULL,
    PRIMARY KEY (date, time, CELL_NAME)
);

-- MySQL table : hourly_huawei_4g_all_counters_2
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_huawei_4g_all_counters_2 (
    date                                     DATE  NOT NULL,
    time                                     TIME  NOT NULL,
    SITE_NAME                                VARCHAR  NULL,
    CELL_NAME                                VARCHAR  NOT NULL,
    eNodeB_ID                                VARCHAR  NULL,
    local_cell_id                            VARCHAR  NULL,
    L_ChMeas_PRB_UL_Used_Avg                 DECIMAL(38, 12)  NULL,
    L_ChMeas_PRB_DL_Used_Avg                 DECIMAL(38, 12)  NULL,
    L_IRATHO_E2W_ExecAttOut                  DECIMAL(38, 12)  NULL,
    L_IRATHO_E2W_ExecSuccOut                 DECIMAL(38, 12)  NULL,
    L_Traffic_User_Avg                       DECIMAL(38, 12)  NULL,
    L_S1Sig_ConnEst_Att                      DECIMAL(38, 12)  NULL,
    L_S1Sig_ConnEst_Succ                     DECIMAL(38, 12)  NULL,
    L_RRC_ConnReq_Att_DelayTol               DECIMAL(38, 12)  NULL,
    L_RRC_ConnReq_Succ_DelayTol              DECIMAL(38, 12)  NULL,
    L_ChMeas_PRB_DL_Avail                    DECIMAL(38, 12)  NULL,
    L_ChMeas_PRB_UL_Avail                    DECIMAL(38, 12)  NULL,
    L_Traffic_ActiveUser_UL_Max              DECIMAL(38, 12)  NULL,
    L_Traffic_ActiveUser_Avg                 DECIMAL(38, 12)  NULL,
    L_Thrp_bits_UE_UL_SmallPkt               DECIMAL(38, 12)  NULL,
    L_Thrp_Time_UE_UL_RmvSmallPkt            DECIMAL(38, 12)  NULL,
    L_E_RAB_FailEst_X2AP                     DECIMAL(38, 12)  NULL,
    PRIMARY KEY (date, time, CELL_NAME)
);

-- MySQL table : hourly_huawei_4g_packet_loss
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_huawei_4g_packet_loss (
    date                                     DATE  NOT NULL,
    time                                     TIME  NOT NULL,
    SITE_NAME                                VARCHAR  NULL,
    CELL_NAME                                VARCHAR  NOT NULL,
    eNodeB_ID                                VARCHAR  NULL,
    local_cell_id                            VARCHAR  NULL,
    L_Traffic_DL_PktUuLoss_Loss              DECIMAL(38, 12)  NULL,
    L_Traffic_DL_PktUuLoss_Tot               DECIMAL(38, 12)  NULL,
    L_Traffic_UL_PktLoss_Loss                DECIMAL(38, 12)  NULL,
    L_Traffic_UL_PktLoss_Tot                 DECIMAL(38, 12)  NULL,
    PRIMARY KEY (date, time, CELL_NAME)
);

-- MySQL table : hourly_arcep_huawei_2g
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_arcep_huawei_2g (
    date                                     DATE  NOT NULL,
    time                                     TIME  NOT NULL,
    Granularity                              VARCHAR  NULL,
    NE_Name                                  VARCHAR  NOT NULL,
    UCELL                                    VARCHAR  NOT NULL,
    Reliability                              VARCHAR  NULL,
    CelDwtm                                  DECIMAL(38, 12),
    TCH_Seiz_Req_HandTrafChan                DECIMAL(38, 12),
    TCH_Seiz_Req_TrafChan                    DECIMAL(38, 12),
    TCH_Seizure_Req_SC                       DECIMAL(38, 12),
    Suc_TCH_Seiz_handTrafChan                DECIMAL(38, 12),
    Suc_TCH_Seiz_TrafChann                   DECIMAL(38, 12),
    Suc_TCH_Seiz_SG                          DECIMAL(38, 12),
    SDCCHDrop                                DECIMAL(38, 12),
    SDCCH_Seiz_Req                           DECIMAL(38, 12),
    Suc_SDCCH_Seiz                           DECIMAL(38, 12),
    TCHDrop_Deno_ARCEP                       DECIMAL(38, 12),
    TCHDrop_Nume_ARCEP                       DECIMAL(38, 12),
    TCHCONG_Deno_ARCEP                       DECIMAL(38, 12),
    TCHCONG_Nume_ARCEP                       DECIMAL(38, 12),
    PRIMARY KEY (date, time, UCELL)
);

-- MySQL table : hourly_arcep_huawei_3g
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_arcep_huawei_3g (
    date                                     DATE  NOT NULL,
    time                                     TIME  NOT NULL,
    Granularity                              VARCHAR  NULL,
    NE_Name                                  VARCHAR  NOT NULL,
    UCELL                                    VARCHAR  NOT NULL,
    Reliability                              VARCHAR  NULL,
    SuccFach                                 DECIMAL(38, 12),
    NCsAbnAMR                                DECIMAL(38, 12),
    NCsRabNor                                DECIMAL(38, 12),
    ULHSTput                                 DECIMAL(38, 12),
    DLHSTput                                 DECIMAL(38, 12),
    SuccD2P                                  DECIMAL(38, 12),
    NormPSRabPCH                             DECIMAL(38, 12),
    CDRF2P                                   DECIMAL(38, 12),
    AbnPSRabD2P                              DECIMAL(38, 12),
    AbnPSRabPCH                              DECIMAL(38, 12),
    AttRabPSBkg                              DECIMAL(38, 12),
    AttRabPSInter                            DECIMAL(38, 12),
    AttRabPSStr                              DECIMAL(38, 12),
    AttRabPSConv                             DECIMAL(38, 12),
    SucRabPSBkg                              DECIMAL(38, 12),
    SucRabPSInter                            DECIMAL(38, 12),
    SucRabPSStr                              DECIMAL(38, 12),
    SucRabPSConv                             DECIMAL(38, 12),
    SuccHSDSCH                               DECIMAL(38, 12),
    SuccEDCH                                 DECIMAL(38, 12),
    AttTmStrCall                             DECIMAL(38, 12),
    AttOrgStrCall                            DECIMAL(38, 12),
    AttTmBkgCall                             DECIMAL(38, 12),
    AttOrgBkgCall                            DECIMAL(38, 12),
    AttTmItrCall                             DECIMAL(38, 12),
    AttOrgItrCall                            DECIMAL(38, 12),
    AttHSDSCH                                DECIMAL(38, 12),
    AttEDCH                                  DECIMAL(38, 12),
    TmStrCall                                DECIMAL(38, 12),
    OrgStrCall                               DECIMAL(38, 12),
    TmBkgCall                                DECIMAL(38, 12),
    OrgBkgCall                               DECIMAL(38, 12),
    TmItrCall                                DECIMAL(38, 12),
    OrgInterCall                             DECIMAL(38, 12),
    AtNorAMRWB                               DECIMAL(38, 12),
    AtCsNorHS                                DECIMAL(38, 12),
    AtCsAbnHS                                DECIMAL(38, 12),
    AtAbnAMRWB                               DECIMAL(38, 12),
    AttAMRWB                                 DECIMAL(38, 12),
    AttAMR                                   DECIMAL(38, 12),
    AttHsCsConv                              DECIMAL(38, 12),
    SucAMRWB                                 DECIMAL(38, 12),
    SucAMR                                   DECIMAL(38, 12),
    SucCSStr                                 DECIMAL(38, 12),
    SucRabEst                                DECIMAL(38, 12),
    SucHsCsConv                              DECIMAL(38, 12),
    AtUnknown                                DECIMAL(38, 12),
    AtTmConvCall                             DECIMAL(38, 12),
    AtOrgSubCall                             DECIMAL(38, 12),
    AtOrgConvCall                            DECIMAL(38, 12),
    AttEmgCall                               DECIMAL(38, 12),
    AttCallReEst                             DECIMAL(38, 12),
    Unknown                                  DECIMAL(38, 12),
    TmConvCall                               DECIMAL(38, 12),
    OrgSubCall                               DECIMAL(38, 12),
    OrgConvCall                              DECIMAL(38, 12),
    NSRRCCEmgCall                            DECIMAL(38, 12),
    NSRRCCallReest                           DECIMAL(38, 12),
    CSStrRabEstReq                           DECIMAL(38, 12),
    CSConvRabEstReq                          DECIMAL(38, 12),
    FailRabEstDlPwrCong                      DECIMAL(38, 12),
    FailRabEstUlPwrCong                      DECIMAL(38, 12),
    FailRabEstCodeCong                       DECIMAL(38, 12),
    FailRabEstDlCECong                       DECIMAL(38, 12),
    FailRabEstUlCECong                       DECIMAL(38, 12),
    FailRabestUlIub                          DECIMAL(38, 12),
    FailRabEstDlIub                          DECIMAL(38, 12),
    PRIMARY KEY (date, time, UCELL)
);

-- MySQL table : hourly_arcep_huawei_4g
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_arcep_huawei_4g (
    date                                     DATE  NOT NULL,
    time                                     TIME  NOT NULL,
    Granularity                              VARCHAR  NULL,
    NE_Name                                  VARCHAR  NOT NULL,
    UCELL                                    VARCHAR  NOT NULL,
    Reliability                              VARCHAR  NULL,
    RABNorrel                                DECIMAL(38, 12),
    ERABAttEst                               DECIMAL(38, 12),
    ERABSucEst                               DECIMAL(38, 12),
    ULHiPre                                  DECIMAL(38, 12),
    ULThrp                                   DECIMAL(38, 12),
    DLHiPre                                  DECIMAL(38, 12),
    DLThrp                                   DECIMAL(38, 12),
    RABAbn                                   DECIMAL(38, 12),
    AttModa                                  DECIMAL(38, 12),
    AttMT                                    DECIMAL(38, 12),
    AttHiPri                                 DECIMAL(38, 12),
    AttEMC                                   DECIMAL(38, 12),
    RRCReqMT                                 DECIMAL(38, 12),
    RRCReqModa                               DECIMAL(38, 12),
    RRCReqHiPri                              DECIMAL(38, 12),
    RRCReqEmc                                DECIMAL(38, 12),
    PRIMARY KEY (date, time, UCELL)
);

-- MySQL table : hourly_ericsson_arcep_2g_counters
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_ericsson_arcep_2g_counters (
    DATE                                     DATE  NOT NULL,
    TIME                                     TIME  NOT NULL,
    CELL_NAME                                VARCHAR  NOT NULL,
    SITE_NAME                                VARCHAR  NULL,
    CONTROLLER_NAME                          VARCHAR  NOT NULL,
    HDWNACC                                  DECIMAL(38, 12)  NULL,
    THNDROP                                  DECIMAL(38, 12)  NULL,
    THNDROPSUB                               DECIMAL(38, 12)  NULL,
    TFNDROP                                  DECIMAL(38, 12)  NULL,
    TFNDROPSUB                               DECIMAL(38, 12)  NULL,
    CNRELCONG                                DECIMAL(38, 12)  NULL,
    CCONGS                                   DECIMAL(38, 12)  NULL,
    CNDROP                                   DECIMAL(38, 12)  NULL,
    TASSALL                                  DECIMAL(38, 12)  NULL,
    TCASSALL                                 DECIMAL(38, 12)  NULL,
    CCALLS                                   DECIMAL(38, 12)  NULL,
    TFTRALACC                                DECIMAL(38, 12)  NULL,
    TFNSCAN                                  DECIMAL(38, 12)  NULL,
    THTRALACC                                DECIMAL(38, 12)  NULL,
    THNSCAN                                  DECIMAL(38, 12)  NULL,
    TFNRELCONG                               DECIMAL(38, 12)  NULL,
    TFNRELCONGSUB                            DECIMAL(38, 12)  NULL,
    THNRELCONG                               DECIMAL(38, 12)  NULL,
    THNRELCONGSUB                            DECIMAL(38, 12)  NULL,
    TFCASSALL                                DECIMAL(38, 12)  NULL,
    TFCASSALLSUB                             DECIMAL(38, 12)  NULL,
    THCASSALL                                DECIMAL(38, 12)  NULL,
    THCASSALLSUB                             DECIMAL(38, 12)  NULL,
    CMSESTAB                                 DECIMAL(38, 12)  NULL,
    TDWNACC                                  DECIMAL(38, 12)  NULL,
    TDWNSCAN                                 DECIMAL(38, 12)  NULL,
    CDISQA                                   DECIMAL(38, 12)  NULL,
    CDISQASUB                                DECIMAL(38, 12)  NULL,
    CDISSS                                   DECIMAL(38, 12)  NULL,
    CDISTA                                   DECIMAL(38, 12)  NULL,
    CDISSSSUB                                DECIMAL(38, 12)  NULL,
    DISNORM                                  DECIMAL(38, 12)  NULL,
    THCTC1                                   DECIMAL(38, 12)  NULL,
    THCTC2                                   DECIMAL(38, 12)  NULL,
    TAVAACC                                  DECIMAL(38, 12)  NULL,
    TAVASCAN                                 DECIMAL(38, 12)  NULL,
    AVG_TNUCHCNT                             DECIMAL(38, 12)  NULL,
    CTRALACC                                 DECIMAL(38, 12)  NULL,
    CNSCAN                                   DECIMAL(38, 12)  NULL,
    DISRET3G                                 DECIMAL(38, 12)  NULL,
    DISRETLTE                                DECIMAL(38, 12)  NULL,
    CCONGSSUB                                DECIMAL(38, 12)  NULL,
    TRAFFIC_DATA_GB                          DECIMAL(38, 12)  NULL,
    TRAFFIC_VOIX                             DECIMAL(38, 12)  NULL,
    HOVERCNTUTRAN                            DECIMAL(38, 12)  NULL,
    HOVERSUCUTRAN                            DECIMAL(38, 12)  NULL,
    HOVERSUC                                 DECIMAL(38, 12)  NULL,
    HOVERCNT                                 DECIMAL(38, 12)  NULL,
    PRIMARY KEY (DATE, TIME, CELL_NAME, CONTROLLER_NAME)
);

-- ------------------ MySQL table : huawei_adjacent_node_id_3g
-- --------------- auto_detect=True  : all VARCHAR, real types inferred on load
CREATE TABLE IF NOT EXISTS huawei_adjacent_node_id_3g (
    adjacent_node_id                         VARCHAR  NOT NULL,
    rnc_adjnode                              VARCHAR  NOT NULL,
    adjacent_node_name                       VARCHAR  NOT NULL,
    site_name                                VARCHAR  NOT NULL,
    rnc                                      VARCHAR  NOT NULL,
    PRIMARY KEY (adjacent_node_id, adjacent_node_name, rnc)
);


-- MySQL table : hourly_ericsson_arcep_3g_counters
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_ericsson_arcep_3g_counters (
    DATE                                     DATE  NOT NULL,
    TIME                                     TIME  NOT NULL,
    CELL_NAME                                VARCHAR  NOT NULL,
    SITE_NAME                                VARCHAR  NULL,
    CONTROLLER_NAME                          VARCHAR  NULL,
    ReqCs                                    DECIMAL(38, 12)  NULL,
    ReqCsSucc                                DECIMAL(38, 12)  NULL,
    ReqPs                                    DECIMAL(38, 12)  NULL,
    ReqPsSucc                                DECIMAL(38, 12)  NULL,
    pmNoDirRetryAtt                          DECIMAL(38, 12)  NULL,
    pmNoLoadSharingRrcConnPs                 DECIMAL(38, 12)  NULL,
    pmNoNormalRabReleasePacket               DECIMAL(38, 12)  NULL,
    pmNoNormalRabReleaseSpeech               DECIMAL(38, 12)  NULL,
    pmNoRabEstablishAttemptPacketInteractive DECIMAL(38, 12)  NULL,
    pmNoRabEstablishAttemptSpeech            DECIMAL(38, 12)  NULL,
    pmNoRabEstablishSuccessPacketInteractive DECIMAL(38, 12)  NULL,
    pmNoRabEstablishSuccessSpeech            DECIMAL(38, 12)  NULL,
    pmNoRabEstBlockTnSpeech                  DECIMAL(38, 12)  NULL,
    pmNoRabEstBlockNodeSpeechBest            DECIMAL(38, 12)  NULL,
    pmNoSystemRabReleasePacket               DECIMAL(38, 12)  NULL,
    pmNoSystemRabReleaseSpeech               DECIMAL(38, 12)  NULL,
    pmNoSuccRbReconfOrigPsIntDch             DECIMAL(38, 12)  NULL,
    pmPsIntHsToFachSucc                      DECIMAL(38, 12)  NULL,
    pmSumEulRlcUserPacketThp                 DECIMAL(38, 12)  NULL,
    pmSamplesEulRlcUserPacketThp             DECIMAL(38, 12)  NULL,
    pmSumEulRlcTotPacketThp                  DECIMAL(38, 12)  NULL,
    pmSamplesEulRlcTotPacketThp              DECIMAL(38, 12)  NULL,
    pmSumHsDlRlcUserPacketThp                DECIMAL(38, 12)  NULL,
    pmSamplesHsDlRlcUserPacketThp            DECIMAL(38, 12)  NULL,
    pmRlAddSuccessBestCellSpeech             DECIMAL(38, 12)  NULL,
    pmRlAddAttemptsBestCellSpeech            DECIMAL(38, 12)  NULL,
    pmNoSuccessOutIratHoSpeech               DECIMAL(38, 12)  NULL,
    pmNoAttOutIratHoSpeech                   DECIMAL(38, 12)  NULL,
    PERIOD_DURATION                          DECIMAL(38, 12)  NULL,
    pmCellDowntimeAuto                       DECIMAL(38, 12)  NULL,
    pmCellDowntimeMan                        DECIMAL(38, 12)  NULL,
    TRAFFIC_DATA_GB                          DECIMAL(38, 12)  NULL,
    TRAFFIC_VOIX                             DECIMAL(38, 12)  NULL,
    pmSumFachPsIntRabEstablish               DECIMAL(38, 12)  NULL,
    pmSumPsHsAdchRabEstablish                DECIMAL(38, 12)  NULL,
    pmSumPsEulRabEstablish                   DECIMAL(38, 12)  NULL,
    pmSumPsInteractive                       DECIMAL(38, 12)  NULL,
    pmNoSuccessOutSbHoSpeech                 DECIMAL(38, 12)  NULL,
    pmSuccLbhoSpeech                         DECIMAL(38, 12)  NULL,
    pmAttLbhoSpeech                          DECIMAL(38, 12)  NULL,
    pmNoAttOutSbHoSpeech                     DECIMAL(38, 12)  NULL,
    PRIMARY KEY (DATE, TIME, CELL_NAME)
);

-- MySQL table : hourly_ericsson_arcep_4g_counters
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_ericsson_arcep_4g_counters (
    DATE                                     DATE  NOT NULL,
    TIME                                     TIME  NOT NULL,
    CELL_NAME                                VARCHAR  NOT NULL,
    SITE_NAME                                VARCHAR  NULL,
    pmRrcConnEstabSucc                       DECIMAL(38, 12)  NULL,
    pmRrcConnEstabAtt                        DECIMAL(38, 12)  NULL,
    pmS1SigConnEstabSucc                     DECIMAL(38, 12)  NULL,
    pmS1SigConnEstabAtt                      DECIMAL(38, 12)  NULL,
    pmErabEstabSuccInit                      DECIMAL(38, 12)  NULL,
    pmErabEstabAttInit                       DECIMAL(38, 12)  NULL,
    pmErabRelAbnormalEnbAct                  DECIMAL(38, 12)  NULL,
    pmErabRelMmeAct                          DECIMAL(38, 12)  NULL,
    pmErabEstabSuccAdded                     DECIMAL(38, 12)  NULL,
    pmPdcpVolDlDrb                           DECIMAL(38, 12)  NULL,
    pmSchedActivityCellDl                    DECIMAL(38, 12)  NULL,
    pmPdcpVolUlDrb                           DECIMAL(38, 12)  NULL,
    pmSchedActivityCellUl                    DECIMAL(38, 12)  NULL,
    pmPdcpPktLostUl                          DECIMAL(38, 12)  NULL,
    pmPdcpPktReceivedUl                      DECIMAL(38, 12)  NULL,
    pmErabRelAbnormalMmeAct                  DECIMAL(38, 12)  NULL,
    pmErabRelAbnormalEnb                     DECIMAL(38, 12)  NULL,
    pmErabRelNormalEnb                       DECIMAL(38, 12)  NULL,
    pmErabRelMme                             DECIMAL(38, 12)  NULL,
    pmRrcConnEstabAttReatt                   DECIMAL(38, 12)  NULL,
    pmPdcpVolDlDrbLastTTI                    DECIMAL(38, 12)  NULL,
    pmErabEstabAttAdded                      DECIMAL(38, 12)  NULL,
    pmUeCtxtRelCsfbGsm                       DECIMAL(38, 12)  NULL,
    pmUeCtxtRelCsfbGsmEm                     DECIMAL(38, 12)  NULL,
    pmUeCtxtRelCsfbWcdma                     DECIMAL(38, 12)  NULL,
    pmUeCtxtRelCsfbWcdmaEm                   DECIMAL(38, 12)  NULL,
    pmUeCtxtEstabAttCsfb                     DECIMAL(38, 12)  NULL,
    pmUeCtxtModAttCsfb                       DECIMAL(38, 12)  NULL,
    pmRrcConnMax                             DECIMAL(38, 12)  NULL,
    pmUeThpTimeDl                            DECIMAL(38, 12)  NULL,
    pmUeThpTimeUl                            DECIMAL(38, 12)  NULL,
    pmPrbUsedDlSrbFirstTrans                 DECIMAL(38, 12)  NULL,
    pmPrbUsedDlDtch                          DECIMAL(38, 12)  NULL,
    pmPrbUsedDlBcch                          DECIMAL(38, 12)  NULL,
    pmPrbUsedDlPcch                          DECIMAL(38, 12)  NULL,
    pmPrbUsedDlFirstTrans                    DECIMAL(38, 12)  NULL,
    pmPrbUsedDlReTrans                       DECIMAL(38, 12)  NULL,
    pmPrbAvailDl                             DECIMAL(38, 12)  NULL,
    pmCellDowntimeMan                        DECIMAL(38, 12)  NULL,
    pmCellDowntimeAuto                       DECIMAL(38, 12)  NULL,
    PERIOD_DURATION                          DECIMAL(38, 12)  NULL,
    pmHoPrepSuccLteIntraF                    DECIMAL(38, 12)  NULL,
    pmHoPrepAttLteIntraF                     DECIMAL(38, 12)  NULL,
    pmHoExeSuccLteIntraF                     DECIMAL(38, 12)  NULL,
    pmHoExeAttLteIntraF                      DECIMAL(38, 12)  NULL,
    pmHoPrepSuccLteInterF                    DECIMAL(38, 12)  NULL,
    pmHoPrepAttLteInterF                     DECIMAL(38, 12)  NULL,
    pmHoExeSuccLteInterF                     DECIMAL(38, 12)  NULL,
    pmHoExeAttLteInterF                      DECIMAL(38, 12)  NULL,
    TRAFFIC_DATA_GB                          DECIMAL(38, 12)  NULL,
    pmRrcConnLevSum                          DECIMAL(38, 12)  NULL,
    pmRrcConnLevSamp                         DECIMAL(38, 12)  NULL,
    pmActiveUeDlSum                          DECIMAL(38, 12)  NULL,
    pmActiveUeUlSum                          DECIMAL(38, 12)  NULL,
    pmHoPrepAtt                              DECIMAL(38, 12)  NULL,
    pmHoPrepSucc                             DECIMAL(38, 12)  NULL,
    pmHoExeAtt                               DECIMAL(38, 12)  NULL,
    pmHoExeSucc                              DECIMAL(38, 12)  NULL,
    pmUeThpVolUl                             DECIMAL(38, 12)  NULL,
    PRIMARY KEY (DATE, TIME, CELL_NAME)
);

-- MySQL table : hourly_ericsson_packet_loss_bb_3g_counters
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_ericsson_packet_loss_bb_3g_counters (
    DATE                                     DATE  NOT NULL,
    TIME                                     TIME  NOT NULL,
    SITE_NAME                                VARCHAR  NOT NULL,
    sctpAssocRtxChunks                       DECIMAL(38, 12)  NULL,
    sctpAssocOutDataChunks                   DECIMAL(38, 12)  NULL,
    PRIMARY KEY (DATE, TIME, SITE_NAME)
);

-- MySQL table : hourly_ericsson_packet_loss_bb_4g_counters
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_ericsson_packet_loss_bb_4g_counters (
    DATE                                     DATE  NOT NULL,
    TIME                                     TIME  NOT NULL,
    SITE_NAME                                VARCHAR  NOT NULL,
    sctpAssocRtxChunks                       DECIMAL(38, 12)  NULL,
    sctpAssocOutDataChunks                   DECIMAL(38, 12)  NULL,
    PRIMARY KEY (DATE, TIME, SITE_NAME)
);

-- MySQL table : hourly_ericsson_packet_loss_du_3g_counters
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_ericsson_packet_loss_du_3g_counters (
    DATE                                     DATE  NOT NULL,
    TIME                                     TIME  NOT NULL,
    SITE_NAME                                VARCHAR  NOT NULL,
    CONTROLLER_NAME                          VARCHAR  NOT NULL,
    pmSctpStatSentChunks                     DECIMAL(38, 12)  NULL,
    pmSctpStatRetransChunks                  DECIMAL(38, 12)  NULL,
    count_pmSctpStatRetransChunks            DECIMAL(38, 12)  NULL,
    count_pmSctpStatSentChunks               DECIMAL(38, 12)  NULL,
    PRIMARY KEY (DATE, TIME, SITE_NAME, CONTROLLER_NAME)
);

-- MySQL table : hourly_ericsson_packet_loss_du_4g_counters
-- auto_detect=False | varchar_to_decimal=True
CREATE TABLE IF NOT EXISTS hourly_ericsson_packet_loss_du_4g_counters (
    DATE                                     DATE  NOT NULL,
    TIME                                     TIME  NOT NULL,
    SITE_NAME                                VARCHAR  NOT NULL,
    pmSctpStatRetransChunks                  DECIMAL(38, 12)  NULL,
    pmSctpStatSentChunks                     DECIMAL(38, 12)  NULL,
    count_pmSctpStatRetransChunks            DECIMAL(38, 12)  NULL,
    count_pmSctpStatSentChunks               DECIMAL(38, 12)  NULL,
    PRIMARY KEY (DATE, TIME, SITE_NAME)
);

-- MySQL table : ept_2g
-- auto_detect=True  : all VARCHAR, real types inferred on load
CREATE TABLE IF NOT EXISTS ept_2g (
    VENDOR                                   VARCHAR  NOT NULL,
    CELL_NAME                                VARCHAR  NOT NULL,
    SITE_NAME                                VARCHAR  NULL,
    BSC                                      VARCHAR  NULL,
    BCCH                                     VARCHAR  NULL,
    BSIC                                     VARCHAR  NULL,
    CELL_ID                                  VARCHAR  NULL,
    LAC                                      VARCHAR  NULL,
    FREQUENCE                                VARCHAR  NULL,
    AZIMUTH                                  VARCHAR  NULL,
    LONGITUDE                                VARCHAR  NULL,
    LATITUDE                                 VARCHAR  NULL,
    ARRONDISSEMENT                           VARCHAR  NULL,
    COMMUNE                                  VARCHAR  NULL,
    DEPARTEMENT                              VARCHAR  NULL,
    PRIMARY KEY (VENDOR, CELL_NAME)
);

-- MySQL table : ept_3g
-- auto_detect=True  : all VARCHAR, real types inferred on load
CREATE TABLE IF NOT EXISTS ept_3g (
    VENDOR                                   VARCHAR  NOT NULL,
    CELL_NAME                                VARCHAR  NOT NULL,
    RBS_NAME                                 VARCHAR  NULL,
    SITE_NAME                                VARCHAR  NULL,
    RNC                                      VARCHAR  NULL,
    LAC                                      VARCHAR  NULL,
    localcellid                              VARCHAR  NULL,
    ServiceArea                              VARCHAR  NULL,
    PSC                                      VARCHAR  NULL,
    FREQ_BAND                                VARCHAR  NULL,
    BANDE                                    VARCHAR  NULL,
    AZIMUTH                                  VARCHAR  NULL,
    LONGITUDE                                VARCHAR  NULL,
    LATITUDE                                 VARCHAR  NULL,
    ARRONDISSEMENT                           VARCHAR  NULL,
    COMMUNE                                  VARCHAR  NULL,
    DEPARTEMENT                              VARCHAR  NULL,
    PRIMARY KEY (VENDOR, CELL_NAME)
);

-- MySQL table : ept_4g
-- auto_detect=True  : all VARCHAR, real types inferred on load
CREATE TABLE IF NOT EXISTS ept_4g (
    VENDOR                                   VARCHAR  NOT NULL,
    CELL_NAME                                VARCHAR  NOT NULL,
    ERBS_Id                                  VARCHAR  NULL,
    SITE_NAME                                VARCHAR  NULL,
    enodb_id                                 VARCHAR  NULL,
    TAC                                      VARCHAR  NULL,
    cell_id                                  VARCHAR  NULL,
    dlchannelbandwidth                       VARCHAR  NULL,
    earfcndl                                 VARCHAR  NULL,
    earfcnul                                 VARCHAR  NULL,
    freq_band                                VARCHAR  NULL,
    PCI                                      VARCHAR  NULL,
    ulchannelbandwidth                       VARCHAR  NULL,
    Bande                                    VARCHAR  NULL,
    AZIMUTH                                  VARCHAR  NULL,
    LONGITUDE                                VARCHAR  NULL,
    LATITUDE                                 VARCHAR  NULL,
    ARRONDISSEMENT                           VARCHAR  NULL,
    COMMUNE                                  VARCHAR  NULL,
    DEPARTEMENT                              VARCHAR  NULL,
    PRIMARY KEY (VENDOR, CELL_NAME)
);
